### ISSUE TITLE
Unable to install on Windows 11 22H2 Pro

### ISSUE THREAD

**Issue by jan-valek** [code-ready/crc#3386] opened 2022-10-16 07:15 UTC
Hi, I tried to install OpenShift Local on Windows 11 22h2 pro but installation is ending prematurely. So I run it again with logging enabled on verbose, and here is the problem:
```
MSI (s) (B8:84) [08:06:52:792]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
MSI (s) (B8:94) [08:06:53:770]: Executing op: ActionStart(Name=AddUserToHypervAdminGroup,Description=Adding user: janva to Hyper-V Administrators group,)
MSI (s) (B8:94) [08:06:53:772]: Executing op: CustomActionSchedule(Action=AddUserToHypervAdminGroup,ActionType=3137,Source=BinaryData,Target=WixQuietExec64,CustomActionData="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NonInteractive -ExecutionPolicy Bypass -NoProfile -Command "Add-LocalGroupMember -Member janva -SID S-1-5-32-578")
MSI (s) (B8:60) [08:06:53:774]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI3D69.tmp, Entrypoint: WixQuietExec64
WixQuietExec64:  Add-LocalGroupMember : degastation\janva is already a member of group S-1-5-32-578.
WixQuietExec64:  At line:1 char:1
WixQuietExec64:  + Add-LocalGroupMember -Member janva -SID S-1-5-32-578
WixQuietExec64:  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec64:      + CategoryInfo          : ResourceExists: (S-1-5-32-578:SecurityIdentifier) , MemberExistsEx 
WixQuietExec64:     ception
WixQuietExec64:      + FullyQualifiedErrorId : MemberExists,Microsoft.PowerShell.Commands.AddLocalGroupMemberCommand
WixQuietExec64:   
WixQuietExec64:  Error 0x80070001: Command line returned an error.
WixQuietExec64:  Error 0x80070001: QuietExec64 Failed
WixQuietExec64:  Error 0x80070001: Failed in ExecCommon method
CustomAction AddUserToHypervAdminGroup returned actual error code 1603 but will be translated to success due to continue marking
MSI (s) (B8:94) [08:06:54:349]: Executing op: ActionStart(Name=EnableFileAndPrinterSharing,Description=Enabling file and printer Sharing,)
MSI (s) (B8:94) [08:06:54:350]: Executing op: CustomActionSchedule(Action=EnableFileAndPrinterSharing,ActionType=3073,Source=BinaryData,Target=WixQuietExec64,CustomActionData="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NonInteractive -ExecutionPolicy Bypass -NoProfile -Command "Set-NetFirewallRule -DisplayGroup 'File And Printer Sharing' -Enabled True -Profile 'Private,Public'")
MSI (s) (B8:DC) [08:06:54:352]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI3FAC.tmp, Entrypoint: WixQuietExec64
WixQuietExec64:  Set-NetFirewallRule : No MSFT_NetFirewallRule objects found with property 'DisplayGroup' equal to 'File And Printer Sha
WixQuietExec64:  ring'.  Verify the value of the property and retry.
WixQuietExec64:  At line:1 char:1
WixQuietExec64:  + Set-NetFirewallRule -DisplayGroup 'File And Printer Sharing' -Enabled ...
WixQuietExec64:  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec64:      + CategoryInfo          : ObjectNotFound: (File And Printer Sharing:String) , CimJobException
WixQuietExec64:      + FullyQualifiedErrorId : CmdletizationQuery_NotFound_DisplayGroup,Set-NetFirewallRule
WixQuietExec64:   
WixQuietExec64:  Error 0x80070001: Command line returned an error.
WixQuietExec64:  Error 0x80070001: QuietExec64 Failed
WixQuietExec64:  Error 0x80070001: Failed in ExecCommon method
CustomAction EnableFileAndPrinterSharing returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 8:06:55: InstallFinalize. Return value 3.
```
First one is OK i think but second one is error. Interesting thing is, that if I run that command from elevated powershell it works without error. Can you help me ?

**Comment by jan-valek** [comment] 2022-10-16 07:31
Attaching full installation log
[install.txt](https://github.com/code-ready/crc/files/9793829/install.txt)

**Comment by marcoshaw** [comment] 2022-10-17 01:23
https://github.com/code-ready/crc/commit/c3e9cf7580cfb5ad56fc8a0196551e871c19bddd

It looks like this was committed just a week ago.  Not sure on the justification for why it was changes.

**Comment by marcoshaw** [comment] 2022-10-17 01:33
Do you maybe have some kind of third party security product that is able to block firewall changes?  It might just be a coincidence that this change was done and you upgraded to 22H2.

**Comment by jan-valek** [comment] 2022-10-17 04:29
No, only which is integrated in windows. Only think that come in my mind is Office 365 business which is importing some domain rules when installed. But this is my 365 with only default setting (I didn't do any policy customization).

**Comment by jan-valek** [comment] 2022-10-17 05:02
OK, I just try to run installer on reinstalled machine. And it works. I did clen reinstall with Windows 11 22h2 installer created by Microsoft media creation tool. With these differences compared to my previous install:  System localization is now Us English, before was Czech language and I dint install any Office 365 product jet. Visual studio, JetBrains toolbox with Rider git and other developer tools was installed in same fashion as before.

**Comment by anjannath** [comment] 2022-10-17 05:37
@jan-valek looks like maybe the issue is with localisation? in the Czech language version the `-DisplayGroup` argument also has to in Czech, if that's the case i think we should force the locale to english temporarily in the powershell session

**Comment by jan-valek** [comment] 2022-10-17 05:42
@anjannath now I don't have machine where I can test it, but I think you are right. I have problem before with Hyper-V admin role, where I have to add user to hyper-v admin group manually. 
What confuses me is why that command worked (not returned error) if was launched from command line? Is there some possibility that in that case Windows do some translation?

**Comment by anjannath** [comment] 2022-10-17 08:34
> What confuses me is why that command worked (not returned error) if was launched from command line? Is there some possibility that in that case Windows do some translation?

ahh, right it did work when you tried manually on powershell.. in that case it doesn't seem like a localization issue, but am not sure if powershell/windows does some automatic translations!

**Comment by jan-valek** [comment] 2022-10-17 09:08
@anjannath maybe I was wrong before, my second work box is on Czech Windows 11 22h2. So now I tried this commands:
` Get-NetFirewallRule -DisplayGroup 'File And Printer Sharing'`
With result:
```
Get-NetFirewallRule: No MSFT_NetFirewallRule objects found with property 'DisplayGroup' equal to 'File And Printer Sharing'.  Verify the value of the property and retry.
```
And this command:
`Get-NetFirewallRule -DisplayGroup 'Sdílení souborů a tiskáren'`
With result: 
```
Name                          : FPS-RPCSS-In-TCP-NoScope
DisplayName                   : Sdílení souborů a tiskáren (služba Zařazování tisku – RPC-EPMAP)
Description                   : Pravidlo příchozí komunikace pro službu RPCSS, které povoluje přenosy protokolu RPC/TCP pro službu Zařazování tisku.
DisplayGroup                  : Sdílení souborů a tiskáren
Group                         : @FirewallAPI.dll,-28502
Enabled                       : False
Profile                       : Domain
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LooseSourceMapping            : False
LocalOnlyMapping              : False
Owner                         :
...
```
And if I run this command:
` Set-NetFirewallRule -DisplayGroup "File And Printer Sharing" -Enabled True -Profile "Private,Public"`
In elevated powershell it crashes too with this result:
```
Set-NetFirewallRule : No MSFT_NetFirewallRule objects found with property 'DisplayGroup' equal to 'File And Printer Sharing'.  Verify the value of the property and retry.
At line:1 char:1
+ Set-NetFirewallRule -DisplayGroup "File And Printer Sharing" -Enabled ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (File And Printer Sharing:String) [Set-NetFirewallRule], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_DisplayGroup,Set-NetFirewallRule
```
So maybe I was wrong before when I said it works. But this behaviour is explaining why is not working. So, I dare to say you are right and it is localization problem.

**Comment by anjannath** [comment] 2022-10-18 05:01
Found this to temporarily force the locale to english: https://stackoverflow.com/questions/59909992/temporarily-change-powershell-language-to-english

**Comment by Drabenstein** [comment] 2022-10-21 15:18
Hi, I've also encountered the same issue on Windows 11 22H2 with pl-PL locale and version 2.10.1. Even changing locale to en-US didn't resolve the issue. Previous version (2.9.0) installed and works just fine.

**Comment by davidvoit** [comment] 2022-10-21 15:49
I can confirm the same problem with a german Windows 10 installation. If I take a look at the microsoft powershell documentation, it says one shouldn't use the string but the @FirewallAPI.dll notation

The group should be @FirewallAPI.dll,-28502
I can confirm this number here:

https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/networking-mpssvc-svc-firewallgroups-firewallgroup-group (XML example)

and on this site: https://windows10dll.nirsoft.net/firewallapi_dll.html (Search for 28502)

-->
Set-NetFirewallRule -Group '@FirewallAPI.dll,-28502' -Enabled True -Profile 'Private,Public'

**Comment by gbraad** [comment] 2022-10-21 16:30
Sorry about this. We will fix this for the next release.
________________________________

**Closed** 2022-10-27 06:49 UTC

**Comment by anjannath** [comment] 2022-10-27 06:58
@jan-valek @Drabenstein Apologies for introducing the bug, as Gerard mentioned next version should come with the fix, or if you want to give a try, artefacts are available from the PR: https://github.com/code-ready/crc/actions/runs/3327436341
