### ISSUE TITLE
Not able to connect to local OpenShift Cluster via CodereadyStudio since CRC 4.2

### ISSUE THREAD

**Issue by k0pper** [code-ready/crc#726] opened 2019-10-15 12:51 UTC
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it: Yes

## CRC version
```bash
# Put the output of `crc version`
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
```
  
## CRC status
```bash
# Put the output of `crc status`
CRC VM:          Running
OpenShift:       Running (v4.2.0-0.nightly-2019-09-26-192831)
Disk Usage:      13.94GB of 32.2GB (Inside the CRC VM)
Cache Usage:     22.46GB
Cache Directory: /Users/myuser/.crc/cache
```

## CRC config
```bash
# Put the output of `crc config view`
<empty>
```

## Host Operating System
```bash
# put the output of `sw_vers` in case of Mac
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G7024
```

### Steps to reproduce
1. install crc (version see above)
2. start cluster
3. crc console

### Expected
Displaying metrics and being able to connect to the cluster via Codereadystudio

### Actual
Since I updated CRC to version 4.2.0-0.nightly-2019-09-26-192831, the cluster is behaving weird:

* The webconsole loads every page with higher load times
* Cluster Health is "Red Hat OpenShift Container Platform is in an error state" and I can't figure out where the problem is
* Loading the projects tab via the console sometimes display the error 
```
Error Loading Projects: Call to /api/kubernetes/apis/project.openshift.io/v1/projects?limit=250 timed out after 20000ms.
```
.. but clicking on "try again" loads the projects eventually. All projects are "active"
* Connecting with the cluster with Codereadystudio fails. Neither OAuth nor Basic Authentication seem to work. Tried with both users kubeadmin and developer
```
 forbidden: User "system:anonymous" cannot get path "/apis" forbidden: User "system:anonymous" cannot get path "/apis"
```

From the console, login into kubeadmin and developer works, also I didn't experience any issues with oc commands manipulating the cluster. Especially the last part relating the failing connection between Codereadystudio and the Openshift cluster is big. Is there something I'm missing?

### Logs
https://gist.github.com/k0pper/b1c64c9bb36a47ffe412fa2518511031

**Comment by praveenkumar** [comment] 2019-10-16 09:59
> Connecting with the cluster with Codereadystudio fails. Neither OAuth nor Basic Authentication seem to work. Tried with both users kubeadmin and developer

@k0pper That is the known issue from CodeReadyStudio side and team is in progress to fixing it. Fix will be available soon.

**Comment by cfergeau** [comment] 2019-11-06 11:50
If the issue is a CodeReady Studio issue, should we close this bug?

**Comment by gbraad** [comment] 2019-11-06 12:08
I think upstream issue should be linked here.

**Comment by cfergeau** [comment] 2019-12-19 14:44
Closing this as there was no activity in more than a month.

**Closed by cfergeau** 2019-12-19 14:44 UTC
