### ISSUE TITLE
failure to restart NetworkManager during setup

### ISSUE THREAD

**Issue by elmiko** [code-ready/crc#276] opened 2019-06-28 14:21 UTC
i am following the [getting started guide](https://code-ready.github.io/crc/), i have a fedora 30 server and a user with sudo access (by password).

when i run the `crc setup` command, i see the following error:

```
$ crc setup
crc - Local OpenShift 4.x cluster
INFO Caching oc binary                            
INFO Setting up virtualization                    
INFO Setting up KVM                               
INFO Installing Libvirt                           
INFO Adding user to libvirt group                 
INFO Enabling libvirt                             
INFO Starting Libvirt service                     
INFO Installing crc-driver-libvirt                
INFO Setting up Libvirt crc network               
INFO Starting Libvirt crc network                 
INFO Writing Network Manager config for crc       
INFO Writing dnsmasq config for crc               
FATA Failed to restart NetworkManager: Executing systemctl action failed:  exit status 1: Job for NetworkManager.service failed because the control process exited with error code.
See "systemctl status NetworkManager.service" and "journalctl -xe" for details. 
```

if i manually run `sudo systemctl restart NetworkManager` and then re-run the setup command it appears to succeed.

is the intention that a user needs to have passwordless access to sudo?

**Comment by robin-owen** [comment] 2019-06-28 15:23
> is the intention that a user needs to have passwordless access to sudo?

No, you do not require passwordless access to the `sudo` command.

Unfortunately, I can't comment directly on the issue that you're experiencing, though.

**Comment by gbraad** [comment] 2019-06-28 15:39
The networkmanager command fails. Could you provide the journal and log of
the unit? eg.

journalctl -u NetworkManager ?

Note: you might need sudo permissions depending on how your system is set
up.

**Comment by elmiko** [comment] 2019-06-28 16:14
@gbraad sadly, i have already fixed this by restarting the NetworkManager manually. i did look at the journal logs for it when it happened and nothing looked suspicious, so i didn't save it sorry.

the user i was running _does_ have sudo privileges, but not passwordless.

**Comment by mrguitar** [comment] 2019-07-03 21:39
I just ran into this too. Here's what I see in the journal:

Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0297] device (crc): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0366] device (crc): Activation: successful, device activated.
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0417] device (crc-nic): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0421] device (crc-nic): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0466] device (crc-nic): Activation: successful, device activated.
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0655] device (crc-nic): state change: activated -> unmanaged (reason 'connection-assumed', sys-iface-state: 'external')
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0662] device (crc): bridge port crc-nic was detached
Jul 03 14:09:56 comacho.local NetworkManager[1021]: <info>  [1562180996.0662] device (crc-nic): released from master device crc
Jul 03 14:09:59 comacho.local systemd[1]: Reloading Network Manager.
Jul 03 14:09:59 comacho.local systemd[7821]: NetworkManager.service: Failed to execute command: No such file or directory
Jul 03 14:09:59 comacho.local systemd[7821]: NetworkManager.service: Failed at step EXEC spawning /usr/bin/dbus-send: No such file or directory
Jul 03 14:09:59 comacho.local systemd[1]: NetworkManager.service: Control process exited, code=exited, status=203/EXEC

It looks like either NetworkManager or this script is expecting dbus-send to be installed. With our new super kickass secure, and reliable dbus implementation, dbus-broker, this binary is split off into a package dbus-utils. (https://fedoraproject.org/wiki/Changes/DbusBrokerAsTheDefaultDbusImplementation)

I'm running on Fedora Silverblue and this package is not part of the default installation, nor should it be IMO.

**Comment by gbraad** [comment] 2019-07-04 05:26
> It looks like either NetworkManager or this script is expecting dbus-send
to be installed.
> I'm running on Fedora Silverblue and this package is not part of the
default installation, nor should it be IMO.

Not related to CRC. Please report this issue to Silverblue.

**Comment by praveenkumar** [comment] 2019-07-04 06:42
@mrguitar hey there, @sinnykumari put a document about running crc with silveblue, we will try to put that on a wiki, I will share with you internally.

**Comment by mrguitar** [comment] 2019-07-05 16:13
Thanks guys. Quick correction the package name is dbus-tools (not -utils) and I can confirm it's commonly installed on Fedora systems, and agreed this is specific to silverblue - which you probably shouldn't go out the way to support here. Cheers!

**Comment by praveenkumar** [comment] 2019-07-11 10:36
@mrguitar Great, it worked for you, closing this issue now.

**Closed by praveenkumar** 2019-07-11 10:36 UTC

**Comment by elmiko** [comment] 2019-07-11 13:10
i just want to note that although it appears @mrguitar has solved this issue, i still get it on fresh fedora 30 installs.

**Comment by Spass1966** [comment] 2020-03-26 16:34
I was just bit by this on a fresh Fedora 31 install. A manual restart of NetworkManager followed by a second `crc setup` appears to have fixed

**Comment by Spass1966** [comment] 2020-03-26 16:35
Suggest issue be opened again.

**Comment by cfergeau** [comment] 2020-03-30 11:05
This seems to be a different issue if you are on f31 and not silverblue. Do you have debug logs of the failed NetworkManager restart?
