### ISSUE TITLE
Increase Cluster storage

### ISSUE THREAD

**Issue by anpati1** [code-ready/crc#801] opened 2019-11-11 14:39 UTC
With CRC config I can expand CPUs and Memory but there is no option to increase storage.
My PC has over 1 TB of disk space and I want to use it for workloads. How can you expand cluster storage?

I'm using latest crc version OpenShift 4.2.2 on Windows Hyper-v with 8 CPUs and 28GB memory

I'm getting following error.
 Filesystem on /dev/sda3 at crc-shdl4-master-0 has only 0.15% available space left and is filling up

**Comment by gbraad** [comment] 2019-11-14 03:49
> and I want to use it for workloads. 

can you explain what you mena with workloads? do you do heavy development? remember, this setup is not meant to be used for 'production' like running of applications. in that case, you are better of running the installer and recreate a single node (as you will also not end up with the certificate issues).

If you really have to use more, this is harder to accomplish on Windows as you will need `qemu-img.exe` to grow the disk.
on windows

**Comment by anpati1** [comment] 2019-11-14 07:47
Hi, I meant exploring and trying new operators such as Code Ready Workspaces, Metering, Openshift Pipeline etc. These provide some real value to us... 

Thanks for sending the link. I will also try on RHEL 7.

**Comment by praveenkumar** [comment] 2019-11-14 08:04
@anpati1 https://github.com/code-ready/crc/issues/127#issuecomment-493429805 is more accurate way of doing it and on the RHEL-7 side there is a bug when you try to increase the size.

I am going to mark this as duplicate of #127 and close it.

**Closed by praveenkumar** 2019-11-14 08:04 UTC
