### ISSUE TITLE
[BUG] container image from local registry failing with IMAGE pull error

### ISSUE THREAD

**Issue by thotz** [code-ready/crc#2078] opened 2021-03-09 10:05 UTC
### General information

  * OS: Linux 
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it ? Yes
  * Running CRC on: Laptop

## CRC version
```bash
#$ crc version
CodeReady Containers version: 1.23.1+be17b141
OpenShift version: 4.7.0 (embedded in executable)
```
  
## CRC status
```bash
# crc status --log-level debug
DEBU CodeReady Containers version: 1.23.1+be17b141 
DEBU OpenShift version: 4.7.0 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/jiffin/.crc/machines/crc/.crc-exist 
DEBU Checking file: /home/jiffin/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /home/jiffin/.crc/bin/crc-driver-libvirt 
DEBU Launching plugin server for driver libvirt   
DEBU Plugin server listening at address 127.0.0.1:39073 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-03-09T15:14:52+05:30" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-03-09T15:14:52+05:30" level=debug msg="Fetching VM..." 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU (crc) DBG | time="2021-03-09T15:14:52+05:30" level=debug msg="GetIP called for crc" 
DEBU (crc) DBG | time="2021-03-09T15:14:52+05:30" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-03-09T15:14:52+05:30" level=debug msg="IP address: 192.168.130.11" 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/jiffin/.crc/machines/crc/id_ecdsa] 
DEBU SSH command results: err: <nil>, output: 32737570816 13567578112 /sysroot 
DEBU Running private SSH command                  
DEBU SSH command succeeded                        
DEBU Unexpected operator status for network: ManagementStateDegraded 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU (crc) DBG | time="2021-03-09T15:14:53+05:30" level=debug msg="Closing plugin on server side" 
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
CRC VM:          Running
OpenShift:       Running (v4.7.0)
Disk Usage:      13.57GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.01GB
Cache Directory: /home/jiffin/.crc/cache
```

## CRC config
```bash
# crc config view
$ crc config view
- consent-telemetry                     : no
- memory                                : 20480
```

## Host Operating System
```bash
# cat /etc/os-release 
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce
Tried to consume local registry container image with following steps(it worked in crc4.5)
  1.  oc login -u kubeadmin https://api.crc.testing:6443
  2.  create demo project, 
  3. oc new-project demo
  4.  logged into podman `podman login -u kubeadmin -p $(oc whoami -t) --tls-verify=false default-route-openshift-image-registry.apps-crc.testing`
  5. pushed image from local registry to crc default registry, `podman push e992013d1946 --tls-verify=false default-route-openshift-image-registry.apps-crc.testing/demo/rook`
  6. oc get is -n demo
 ```console
NAME   IMAGE REPOSITORY                                                    TAGS     UPDATED
ceph   default-route-openshift-image-registry.apps-crc.testing/demo/ceph   latest   16 seconds ago
rook   default-route-openshift-image-registry.apps-crc.testing/demo/rook   latest   41 seconds ago
````
  7. oc set image-lookup --all
```console
imagestream.image.openshift.io/ceph image lookup updated
imagestream.image.openshift.io/rook image lookup updated
```
8. pulling image failed, pod didn't start up
```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       31s                default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-87758ddf6-c7pht to crc-l6qvn-master-0
  Normal   AddedInterface  29s                multus             Add eth0 [10.217.0.91/23]
  Normal   Pulling         17s (x2 over 29s)  kubelet            Pulling image "default-route-openshift-image-registry.apps-crc.testing/demo/rook:latest"
  Warning  Failed          17s (x2 over 29s)  kubelet            Failed to pull image "default-route-openshift-image-registry.apps-crc.testing/demo/rook:latest": rpc error: code = Unknown desc = error pinging docker registry default-route-openshift-image-registry.apps-crc.testing: Get "https://default-route-openshift-image-registry.apps-crc.testing/v2/": x509: certificate signed by unknown authority
  Warning  Failed          17s (x2 over 29s)  kubelet            Error: ErrImagePull
  Normal   BackOff         3s (x3 over 28s)   kubelet            Back-off pulling image "default-route-openshift-image-registry.apps-crc.testing/demo/rook:latest"
  Warning  Failed          3s (x3 over 28s)   kubelet            Error: ImagePullBackOff
```

### Expected
Images from the local registry need to consume, pod should come up properly

### Actual
Pod didn't come up with image pull error
```
rook-ceph-operator-55ccf56f56-tlzxr   0/1     ErrImagePull   0          28m
```

**Comment by praveenkumar** [comment] 2021-03-09 11:25
@thotz https://github.com/code-ready/crc/issues/821#issuecomment-555862714 is worked and should be working, Can you try that once?

**Comment by praveenkumar** [comment] 2021-03-09 12:24
Also if that doesn't work then use `image-registry.openshift-image-registry.svc:5000/demo/rook:latest` which is internal registry url and have vaild certs.

**Comment by thotz** [comment] 2021-03-09 18:25
> image-registry.openshift-image-registry.svc:5000/

@praveenkumar : still have the same error

```logs
 Normal   Scheduled       15s                default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-6845bb55bc-2sb2j to crc-l6qvn-master-0
  Normal   AddedInterface  14s                multus             Add eth0 [10.217.0.48/23]
  Normal   BackOff         12s (x2 over 13s)  kubelet            Back-off pulling image "image-registry.openshift-image-registry.svc:5000/demo/rook:latest"
  Warning  Failed          12s (x2 over 13s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling         1s (x2 over 13s)   kubelet            Pulling image "image-registry.openshift-image-registry.svc:5000/demo/rook:latest"
  Warning  Failed          1s (x2 over 13s)   kubelet            Failed to pull image "image-registry.openshift-image-registry.svc:5000/demo/rook:latest": rpc error: code = Unknown desc = Error reading manifest latest in image-registry.openshift-image-registry.svc:5000/demo/rook: unauthorized: authentication required
  Warning  Failed          1s (x2 over 13s)   kubelet            Error: ErrImagePull
```

**Comment by praveenkumar** [comment] 2021-03-11 06:05
@thotz I am not sure how this is not working for you but I again tried following and it does work.

```
$ oc get is
NAME          IMAGE REPOSITORY                                                           TAGS     UPDATED
mytestimage   default-route-openshift-image-registry.apps-crc.testing/demo/mytestimage   latest   40 hours ago

$ cat test.yaml 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest
    name: test
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

$ oc create -f test.yaml

$ oc get events
15s         Normal    Scheduled        pod/test   Successfully assigned demo/test to crc-m7q2f-master-0
12s         Normal    AddedInterface   pod/test   Add eth0 [10.217.1.18/23]
12s         Normal    Pulling          pod/test   Pulling image "image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest"
11s         Normal    Pulled           pod/test   Successfully pulled image "image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest" in 459.506947ms
11s         Normal    Created          pod/test   Created container test
11s         Normal    Started          pod/test   Started container test

```

**Comment by thotz** [comment] 2021-03-11 14:49
@praveenkumar : The difference from [#821 (comment)](https://github.com/code-ready/crc/issues/821#issuecomment-555862714), I am using podman instead of docker and also added `--tls-verify=false` while login and push images.

Is there any way to check the access to registry fine for crc machine?

If require steps for debugging please let me know

**Comment by praveenkumar** [comment] 2021-03-12 02:56
@thotz I am also using `podman` just aliased `docker=podman` and using `--tls-verify=false`, I don't think it is issue with podman/docker because you are able to push the image successfully and it also appear in the imagestream `oc get is` , can you start from fresh and just try with a sample image like I mentioned in https://github.com/code-ready/crc/issues/821#issuecomment-555862714 just to make sure if that is something with image or the issue is somewhere else.

**Comment by thotz** [comment] 2021-03-14 17:32
@praveenkumar : It works for the test image in my setup as mentioned in #821 (comment)](https://github.com/code-ready/crc/issues/821#issuecomment-555862714). But if I change the namespace it won't work. Now if pushed images to the namespace the where my pod is running it is working fine. Not sure it is bug or not

**Comment by praveenkumar** [comment] 2021-03-15 07:25
@thotz Ah I thought you are running the pod in the same namespace as your imagestream. I have to check if it is possible to use the imagestream across namespace and update you. Good to know we have identified the actual issue.

**Comment by praveenkumar** [comment] 2021-03-17 07:42
@thotz https://docs.openshift.com/container-platform/4.7/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-across-projects_using-image-pull-secrets document around how to use image across different project and I did try which worked for me. Please close this issue once you try it out and works for you.

```
$ oc project
Using project "demo" on server "https://api.crc.testing:6443".

$ oc get is
NAME          IMAGE REPOSITORY                                                           TAGS     UPDATED
mytestimage   default-route-openshift-image-registry.apps-crc.testing/demo/mytestimage   latest   2 hours ago

$ oc new-project test
$ oc policy add-role-to-user system:image-puller system:serviceaccount:test:default --namespace=demo
$ cat test.yaml 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest
    name: test
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

$ oc create -f test.yaml 
pod/test created

 $ oc get events
LAST SEEN   TYPE     REASON             OBJECT           MESSAGE
54s         Normal   CreatedSCCRanges   namespace/test   created SCC ranges
3s          Normal   Scheduled          pod/test         Successfully assigned test/test to crc-m7q2f-master-0
1s          Normal   AddedInterface     pod/test         Add eth0 [10.217.1.107/23]
0s          Normal   Pulling            pod/test         Pulling image "image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest"
0s          Normal   Pulled             pod/test         Successfully pulled image "image-registry.openshift-image-registry.svc:5000/demo/mytestimage:latest" in 369.120563ms
0s          Normal   Created            pod/test         Created container test
0s          Normal   Started            pod/test         Started container test
```

**Comment by thotz** [comment] 2021-03-19 07:03
It worked with `testimage` by adding role fro rook-ceph default SA. Hence closing this issue
@praveenkumar : Thanks for helping out

**Closed** 2021-03-19 07:03 UTC
Labels: kind/bug
