### ISSUE TITLE
[BUG] crc ip returns localhost (127.0.0.1)

### ISSUE THREAD

**Issue by jskazinski** [code-ready/crc#2639] opened 2021-08-11 19:50 UTC
### General information

  * OS: Windows 10 Enterprise, Version 20H2 (OS Build 19042.1110)
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Desktop

## CRC version
```bash
CodeReady Containers version: 1.30.1+376cc3c1
OpenShift version: 4.8.2 (embedded in executable)
```
  
## CRC status
```bash
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
PS C:\Users\705882> crc config view
- consent-telemetry                     : no
- kubeadmin-password                    : xxxxxxx
- memory                                : 16384
- pull-secret-file                      : C:\crc\pull-secret.txt
```

## Host Operating System
```bash
PS C:\Users\705882> systeminfo

Host Name:                 COL-M071164D010
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Seagate IT
Registered Organization:   Seagate
Product ID:                00329-00000-00003-AA526
Original Install Date:     8/4/2021, 5:16:26 PM
System Boot Time:          8/7/2021, 12:59:19 PM
System Manufacturer:       Dell Inc.
System Model:              Precision Tower 3620
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~4200 Mhz
BIOS Version:              Dell Inc. 2.13.1, 6/14/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     32,640 MB
Available Physical Memory: 10,828 MB
Virtual Memory: Max Size:  37,504 MB
Virtual Memory: Available: 14,395 MB
Virtual Memory: In Use:    23,109 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    ad.seagate.com
Logon Server:              \\LCOPIADSW003
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB5003537
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4589212
                           [07]: KB4593175
                           [08]: KB4598481
                           [09]: KB5004237
                           [10]: KB5003742
Network Card(s):           4 NIC(s) Installed.
                           [01]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: VMware Network Adapter VMnet1
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.198.254
                                 IP address(es)
                                 [01]: 192.168.198.1
                                 [02]: fe80::6d18:abd0:73c9:4658
                           [02]: VMware Virtual Ethernet Adapter for VMnet8
                                 Connection Name: VMware Network Adapter VMnet8
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.219.254
                                 IP address(es)
                                 [01]: 192.168.219.1
                                 [02]: fe80::8c96:295:8f14:891c
                           [03]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.30.96.1
                                 [02]: fe80::614c:d007:c829:4dc1
                           [04]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.30.16.120
                                 IP address(es)
                                 [01]: 10.31.46.169
                                 [02]: fe80::e80d:8168:3509:2c0d
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. crc delete -f
  2. crc cleanup
  3. Added Local User 705882 to crc-users
  4. Added Hyper-V External Switch 'crc' with External network connection: Intel(R) Ethernet Connection (2) I219-LM
  5. crc setup --log-level debug
  6. reboot
  7. crc setup --log-level debug
  8. crc start --log-level debug
  9. crc start --log-level debug

### Expected

crc ip (NOT 127.0.0.1)
Expect to ssh into core@`crc ip`

### Actual

INFO CodeReady Containers instance is running with IP 127.0.0.1
crc ip is 127.0.0.1
ssh -i C:\Users\705882\.crc\machines\crc\id_ecdsa core@127.0.0.1
ssh: connect to host 127.0.0.1 port 22: Connection refused

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Log Data: https://gist.github.com/jskazinski/6deacc3b1ce079db486e76d4c315e572

(done) Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by guillaumerose** [comment] 2021-08-11 19:56
We use an userland network stack now on Windows and macOS. 
The IP is correct. For ssh, the port is 2222,  not 22 in this configuration.

**Comment by jskazinski** [comment] 2021-08-11 22:49
Thank you, ssh using port 2222 did work.

**Comment by praveenkumar** [comment] 2021-08-12 02:21
Closing this one since it is expected behavior.

**Closed by praveenkumar** 2021-08-12 02:21 UTC
Labels: kind/bug, status/need triage

**Comment by gbraad** [comment] 2021-08-12 03:13
Please note that:

> Added Hyper-V External Switch 'crc' with External network connection: Intel(R) Ethernet Connection (2) I219-LM

is not functional when using the user mode networking stack. This was a fallback to allow you to configure the network to use in case of interVM connection or VPN.

**Comment by jskazinski** [comment] 2021-08-12 13:44
Thank you
