### ISSUE TITLE
[BUG] crc start fails for non-admin users on Windows

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#1691] opened 2020-11-18 01:53 UTC
### General information

  * OS: Windows
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
CodeReady Containers version: 1.18.0+bb304aa
OpenShift version: 4.6.1 (embedded in binary)
```

## Host Operating System
```bash
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

crc start fails if the user does not have admin rights. 
It prompts for an admin user to configure the DNS but fails if such credentials can not be provided.

```bash 
...
INFO Will run as admin: add dns server address to interface vEthernet (Default Switch)
Error running post start: Nameserver 172.17.136.19 not successfully set on interface vEthernet (Default Switch)
```

**Comment by gbraad** [comment] 2020-11-18 04:29
This is a requirement and part of the documentation (annd by design; hence the error). There is at the moment no way around this, as addig the DNS entries to the virtual switch needs admin privileges.

We are however looking into an altternative using the hosts file for quitte some timme, though this also needs admin or installer/setup privileges. the workaround could be an admin helper tool, which runs with privileges to perform certain tasks specfic to crc with elevated privileges

**Comment by gbraad** [comment] 2020-11-18 04:33
Dup of: https://github.com/code-ready/crc/issues/1175 https://github.com/code-ready/crc/issues/1256
Solutions looked into in: https://github.com/code-ready/crc/issues/1132, https://github.com/code-ready/crc/pull/1537

Closing, as this is a known limitation, documented as https://github.com/code-ready/crc/commit/59fcb05c1bac7c2134845477b148ecd4e03c87f8 and has been part of the release notes for quite a while.

**Closed by gbraad** 2020-11-18 04:33 UTC
Labels: kind/bug

**Comment by gorkem** [comment] 2020-11-18 14:40
I actually looked into the docs but looked under _Minimum System Requirements_. Regardless this has been reported 4 times so far (perhaps more). I am a new wins user and tried crc on wins at version 1.17 for the first time and rage quit due to this error. This needs a better response on CRC, perhaps link to docs on the error and explanation on how to remediate?

When I read #1537 I do not read that it will improve the situation for windows. Will it @guillaumerose ?

**Comment by guillaumerose** [comment] 2020-11-18 15:33
#1537 will not help at first. We need to create an admin daemon https://github.com/code-ready/crc/issues/1652 and extract all the steps that the admin needs to perform in a powershell script eg:

``` 
// Activate Hyper-V
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

// Activate userland network stack communication
$service = New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\GuestCommunicationServices" -Name "00000400-FACB-11E6-BD58-64006A7986D3"
$service.SetValue("ElementName", "gvisor-tap-vsock")

// Run the admin daemon as service
something!
```

**Comment by gbraad** [comment] 2020-11-24 06:28
The problem for Hyper-V is that the Default Switch hands out addresses in a range using DHCP, we can't predict or pre-claim an eentry in the hosts-file. This is why we need to get the VM IP, and wwe use that to set using `set-dnsclientserveraddress` to force the VM to act as a nameserver.

> This needs a better response on CRC, perhaps link to docs on the error and explanation on how to remediate?

@kowen any idea how to make users more aware of this?
