### ISSUE TITLE
[BUG] Ensure file permissions are RW for needed files

### ISSUE THREAD

**Issue by RickJWagner** [code-ready/crc#639] opened 2019-09-25 12:57 UTC
### General information

  * OS: macOS 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

This ticket is the result of a user discussion, the usual requested artifacts are no longer available.  Sorry for that.

Problem:  CRC would not start because permissions were 'R', not 'RW' for directories holding:
/etc/resolver/testing
/etc/hosts

When the user made the directories 'RW', CRC started.

**Comment by RickJWagner** [comment] 2019-09-25 12:59
SA Bill Novak has more information if needed.

**Comment by cfergeau** [comment] 2019-09-25 13:00
This is already fixed in git
Duplicate of #618

**Closed** 2019-09-25 13:00 UTC
Labels: kind/bug
