### ISSUE TITLE
[BUG] Windows Setup: Virtual Switch not Found 

### ISSUE THREAD

**Issue by rootameen** [code-ready/crc#560] opened 2019-09-08 20:58 UTC
### General information

  * OS: Windows 10 1903
  * Hypervisor: Hyper-V

## CRC version
`crc-windows-1.0.0-beta.3-amd64`

### Steps to reproduce

  1. Download CRC Package
  2. Add crc Binary to PATH
  3. run `crc setup`

### Expected
Installation should proceed as default switch exists

### Actual
Installation fails with error: Virtual Switch not Found

### Logs

```
\> crc setup --log-level debug
INFO Caching oc binary
DEBU oc binary already cached
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
DEBU Always add user
INFO Does the Hyper-V virtual switch exist
ERRO Error occurred: Virtual Switch not found
DEBU Virtual Switch not found
ERRO Error occurred: Please override the default by adding an external virtual switch and set configuration
FATA Please override the default by adding an external virtual switch and set configuration
```

**Comment by jds2001** [comment] 2019-09-09 02:11
Duplicate of #558 that I opened. Make sure that you logout after running it to ensure that you really are a member of the Hyper-V Administrators group. The Powershell cmdlet `Get-VMSwitch` should execute without error as a normal user (NOT in an elevated Powershell)

**Comment by gbraad** [comment] 2019-09-09 03:14
As mntioned, please relogin to make sure you are a member of the Hyper-V Administrators group.

**Comment by gbraad** [comment] 2019-09-09 03:17
We need to modify the message or detection somehow... the user check never worked well to do this, as it would return you are a member (but it wasn't activate as you can see with the vswitch check).

**Comment by gbraad** [comment] 2019-09-09 03:33
'the user check would return he is a member, but we find out an admin call that needs these privileges fails'...

hold on

hmmm... HEY! We can actually use this as a trick to optimize this check. We check for the user being part of the group. If not, we add him... at the end we perform a simple get-vmswitch and see if it fails, to determine IF a reboot/relogin is needed

**Comment by gbraad** [comment] 2019-09-10 08:22
Updated the message and use `Get-VMSwitch` to determine if admin privileges are given

**Comment by anjannath** [comment] 2020-01-03 08:31
Fixed in https://github.com/code-ready/crc/commit/afd92ec059b26e5fe6ed85f823e676bfb000a6b1

**Closed by anjannath** 2020-01-03 08:31 UTC
Labels: kind/bug, os/windows, priority/major, size/S

**Comment by enriquejavier** [comment] 2020-01-24 04:28
While troubleshooting the error below on my Windows 10 machine

> ERRO Error occurred: Virtual Switch not found

running the PowerShell cmdlet **Get-VMSwitch** gave me the following error:

> Hyper-V encountered an error trying to access an object on computer [_hostname_] because the object was not found. The object might have been deleted...

this is what fixed it:

Run the following command from an Elevated (Administrator) command prompt or PowerShell.
`MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof`

See details here [FIX: Hyper-V encountered...](https://shauncassells.wordpress.com/2018/05/24/fix-hyper-v-encountered-an-error-trying-to-access-an-object-on-computer-localhost-because-the-object-was-not-found-the-object-might-have-been-deleted-verify-that-the-virtual-machine-managemen/)

**Comment by gbraad** [comment] 2020-01-24 05:03
Are you using BTW Windows 10 Enterprise?

**Comment by enriquejavier** [comment] 2020-01-29 18:12
> @enriquejavier ~Are you using BTW Windows 10 Enterprise?~ This is a non-standard situation, and likely caused by either a reconfig on the system. What did you do in recent time that prevented access to the Hyper-V cmdlets?

OS is Windows 10 Professional; I suspect the condition was related to having previously installed VirtualBox;  but there is nothing special about this system.

However, on another system running Windows 10 Enterprise, the same “solution” did not work; in that case I had to completely remove the Hyper-V features from the system, and enable them back for CRC to get going.

**Comment by chrismajewski** [comment] 2020-03-07 00:08
## Environment
Win 10 Enterprise
Behind corporate firewall
Set HTTP_PROXY and HTTPS_PROXY accordingly

## Group

I'm in the *Hyper-V Administrators* group​

## Switch

Added "Default Switch", rebooted

(non elevated powershell) λ  Get-VMSwitch

```
Name           SwitchType NetAdapterInterfaceDescription
----           ---------- ------------------------------
Default Switch External   Broadcom NetXtreme Gigabit Ethernet
```

## Still no dice, can't find switch  (non elevated powershell)

```
(non elevated powershell) λ  crc setup --log-level debug
DEBU HTTP-PROXY: http://--correct-proxy--:80, HTTPS-PROXY: http://--correct-proxy--:80, NO-PROXY: 127.0.0.1,localhost
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
DEBU Virtual Switch not found
ERRO Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
FATA Unable to perform Hyper-V administrative commands. Please make sure to re-login or reboot your system
​```

**Comment by chrismajewski** [comment] 2020-03-10 14:27
Dug through the code, found that it was looking for a switch explicitly named **crc**.

Renaming my hyper-v virtual switch to **crc** and it setup without issue.

**Comment by mikeKuzmin** [comment] 2020-03-13 15:37
> Dug through the code, found that it was looking for a switch explicitly named **crc**.
> 
> Renamed my Hyper-v virtual switch to **crc** and it setup without issue.

That worked, thanks a lot!

**Comment by talk2gopijj** [comment] 2020-08-19 13:07
This fix worked thanks!
