### ISSUE TITLE
crc start fails after stopped 

### ISSUE THREAD

**Issue by gorkem** [code-ready/crc#443] opened 2019-08-21 12:48 UTC
I have version: 0.90.0-alpha-4.1.9+b2559b5. This is all the information that I see on the terminal. I am on Mac on hyperkit
```
INFO Checking if oc binary is cached
INFO Checking if HyperKit is installed
INFO Checking if crc-driver-hyperkit is installed
INFO Checking file permissions for /etc/resolver/testing
INFO Checking file permissions for /etc/hosts
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Extracting bundle: crc_hyperkit_4.1.9.crcbundle ...
INFO Starting stopped VM ...
ERRO Error occurred: Failed to connect to the crc VM with SSH
```

**Comment by cfergeau** [comment] 2019-08-21 14:29
Can you try running `crc delete; crc start --log-level debug` and paste the output?

**Comment by gorkem** [comment] 2019-08-21 17:02
Attached the log 
[Log at 2019-08-21 1-02-05 PM.txt](https://github.com/code-ready/crc/files/3526442/Log.at.2019-08-21.1-02-05.PM.txt)

**Comment by gorkem** [comment] 2019-08-21 17:03
Not sure if it matters but `crc start` works after a `crc delete`

**Comment by gbraad** [comment] 2019-08-26 09:52
Likely related to https://github.com/code-ready/snc/issues/84

**Comment by cfergeau** [comment] 2019-09-19 13:22
Yes, it's likely to be #325

**Comment by cfergeau** [comment] 2019-09-19 13:23
Duplicate of #325

**Closed by cfergeau** 2019-09-19 13:23 UTC
Labels: kind/bug, os/macos, priority/major, state/need more information
