### ISSUE TITLE
ERRO Error running post start: Nameserver not successfully set

### ISSUE THREAD

**Issue by csofiah** [code-ready/crc#1256] opened 2020-05-27 23:29 UTC
I have this problem when I try to config CRC in my PC Windows 10 Pro.
I run:
`crc setup`
`crc start`
and I obtain this error 
```
INFO Loading bundle: crc_hyperv_4.4.3.crcbundle ...
INFO Checking size of the disk image C:\Users\usuario\.crc\cache\crc_hyperv_4.4.3\crc.vhdx ...
INFO Creating CodeReady Containers VM for OpenShift 4.4.3...
INFO CodeReady Containers VM is running
INFO Verifying validity of the cluster certificates ...
INFO Will run as admin: add dns server address to interface vEthernet (Modificador predeterminado)
ERRO Nameserver not successfully set
ERRO Error running post start: Nameserver not successfully set
```
Please I need to help for install the CRC. Thanks

**Comment by gbraad** [comment] 2020-05-28 02:45
> INFO Will run as admin: add dns server address to interface vEthernet (Modificador predeterminado)
> ERRO Nameserver not successfully set
> ERRO Error running post start: Nameserver not successfully set

An UAC request will popup that needs to be confirmed. This sets the DNS for the Virtual Switch to point to the VM. We have concluded after this step that this failed.

**Comment by csofiah** [comment] 2020-05-28 15:19
Hello gbraad, sorry I don't understood your answer. How can I set the nameserver in CRC?

**Comment by gbraad** [comment] 2020-05-29 07:03
This should happen automatically with an UAC request: Administrator privileges are requested. Did you see a  "Yes, allow" or "Cancel" dialog? If not, please re-run and confirm if this happens or not.

That will be requested at:
```
INFO Will run as admin: add dns server address to interface vEthernet (Modificador predeterminado)
```

**Comment by csofiah** [comment] 2020-05-29 14:49
No, I didn't see any dialog for this question, only show the log that I sent you. Exist some way to set de DNS for the Virtsual Switch?Thanks

**Comment by skabashnyuk** [comment] 2020-07-20 12:51
I got into the same trouble. The reason for that was that system configured not to ask the user additional questions in case if application wants to make some adjustments.

**Comment by SkylarScaling** [comment] 2020-07-20 18:47
I also ran into this issue, and here's what I did to resolve it for anyone who wants to try:
crc stop
crc config set nameserver 8.8.8.8 (This may be unnecessary, but I did it because I had deleted my DNS settings for the Virtual Switch)
crc delete --clear-cache
crc delete
crc setup (This now prompted again for the UAC confirmation)
crc start

Hope this helps! Took me 2 days to get it working again!

**Comment by praveenkumar** [comment] 2020-08-28 10:41
I am hoping it is working now for reporter, since there is no more communication, closing this now.

**Closed by praveenkumar** 2020-08-28 10:41 UTC
Labels: os/windows

**Comment by vyom-soft** [comment] 2020-12-02 15:30
> I also ran into this issue, and here's what I did to resolve it for anyone who wants to try:
> crc stop
> crc config set nameserver 8.8.8.8 (This may be unnecessary, but I did it because I had deleted my DNS settings for the Virtual Switch)
> crc delete --clear-cache
> crc delete
> crc setup (This now prompted again for the UAC confirmation)
> crc start
> 
> Hope this helps! Took me 2 days to get it working again!

I am also facing the same issue with the latest version of CRC. 
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)

at the step crc setup  No prompt came up.
crc start  (this prompted UAC confirmation)
But it did not helped 
level=info msg="Will run as admin: add dns server address to interface vEthernet (Default Switch)"
Error running post start: Nameserver 192.168.145.68 not successfully set on interface vEthernet (Default Switch)

**Comment by guillaumerose** [comment] 2020-12-03 10:41
@vyom-soft Last crc release introduced a new network mode that should solve your issue. Can you try it ? https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack Thanks.

**Comment by vyom-soft** [comment] 2020-12-03 18:25
> @vyom-soft Last crc release introduced a new network mode that should solve your issue. Can you try it ? https://github.com/code-ready/crc/wiki/VPN-support--with-an--userland-network-stack Thanks.

Thank you. I tried the latest crc with same steps as mentiond. 
I get the following error:
error: dial tcp: lookup api.crc.testing: no such host - verify you have provided the correct host and port and that the server is currently running.
$crc status
CRC VM:          Running
OpenShift:       Degraded (v4.6.3)
Disk Usage:      12.53GB of 32.72GB (Inside the CRC VM)
Cache Usage:     17.53GB
Cache Directory: C:\Users\don\.crc\cache
