### ISSUE TITLE
Error attempting to get plugin server address for RPC/ Windows10 / Hyper-V

### ISSUE THREAD

**Issue by Jalaa001** [code-ready/crc#950] opened 2020-01-22 11:23 UTC
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.3.0+918756b
OpenShift version: 4.2.10 (embedded in binary)
```
  
## CRC status
```bash
Machine 'crc' does not exist. Use 'crc start' to create it.
```

## CRC config
```bash

```

## Host Operating System
```bash
Time Zone:                                       (UTC+01:00) Brüssel, Kopenhagen, Madrid, Paris
Total Physical Memory:                       16.236 MB
Available Physical Memory:                    9.508 MB
Virtual Memory: Max Size:                    18.668 MB
Virtual Memory: Available:                   10.443 MB
Virtual Memory: In Use:                       8.225 MB
Page File Location(s):                        C:\pagefile.sys
Domain:                                          one.com
Logon Server:                                  \\DC1ONE
Hotfix(s):                                          8 Hotfix(s) installed.
                                                       [01]: KB4533013
                                                       [02]: KB4465065
                                                       [03]: KB4480056
                                                       [04]: KB4512577
                                                       [05]: KB4516115
                                                       [06]: KB4521862
                                                       [07]: KB4523204
                                                       [08]: KB4522015
Network Card(s):                              3 NIC(s) installed.
                                               [01]: Intel(R) Dual Band Wireless-AC 8265
                                                     Connection Name: WLAN
                                                     Status:          Media disconnected
                                               [02]: Intel(R) Ethernet Connection (4) I219-LM
                                                     Connection Name: Ethernet
                                                     DHCP Enabled:  Yes
                                                     DHCP Server:     139.2.50.37
                                                     IP adresse(es)
                                                     [01]: 139.2.50.153
                                                     [02]: fe80::3849:d6e3:4da1:6b47
                                               [03]: Hyper-V Virtual Ethernet Adapter
                                                     Connection Name: vEthernet (Default Switch)
                                                     DHCP Enabled:  Yes
                                                     DHCP Server:     255.255.255.255
                                                     IP adresse(es)
                                                     [01]: 172.17.69.1
```

### Steps to reproduce

  1. crc setup
  2. crc start

### Expected

crc starting

### Actual
```bash
 crc start --log-level debug
DEBU Unable to find out if a new version is available: Get https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
INFO Checking if running as normal user
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Checking file: C:\Users\jlaabs\.crc\machines\crc\.crc-exist
? Image pull secret [? for help] *..*
INFO Loading bundle: crc_hyperv_4.2.10.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.10...
Found binary path at C:\users\jlaabs\Downloads\crc-windows-amd64\crc-windows-1.3.0-amd64\crc.exe
Launching plugin server for driver hyperv
ERRO Error creating host: Error creating new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```
### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue..

**Comment by alekonko** [comment] 2020-03-07 23:27
hi i've same problem. did you resolve?

**Comment by gbraad** [comment] 2020-03-08 04:23
Duplicate of #1021

**Closed by gbraad** 2020-03-08 04:23 UTC
