### ISSUE TITLE
Request: Add --machine-readable option for crc console

### ISSUE THREAD

**Issue by morningspace** [code-ready/crc#713] opened 2019-10-13 13:58 UTC
For minishift, when run `minishift console`, it provides an option called `--machine-readable`, which can print OpenShift's IP, port and Web Console URL in machine readable format. It would be nice if CRC can support this as well.

Just to give an example, where I was trying to integrate CRC into our dev sandbox for OpenShift 4.x use. In order to automate the flow by some scripts, I need the kubeadmin password. Currently, I have to extract it from the `crc console` output using `--credential` as below:
```shell
$ crc console --credentials | grep kubeadmin | sed "s/.*password is '\(.*\)'./\1/"
```

This is not very reliable in case the output text is changed.

Or, if there's any better idea?

**Comment by gbraad** [comment] 2019-10-13 14:16
After our GA output strings should not change.

We will see what can be done about optimizations; for one, we wanted to add an option to allow command results to be returned in a JSON format: #13

**Comment by morningspace** [comment] 2019-10-14 03:32
Yeah, to allow output in JSON would also be helpful...

Ideally, it would be good to see the consistent interface between crc and minishift as much as possible, so that, for example, those are familiar w/ minishift would be easy to move to crc when start to work on OpenShift 4.x, but that depends on how crc is designed :-)

**Comment by cfergeau** [comment] 2019-10-14 09:52
Should this be closed as a duplicate of #13 ? Or do we keep this open to remember it would be useful to prioritize `crc console`?

**Comment by gbraad** [comment] 2019-10-14 10:03
Leave open. We can prioritize and discuss specific needs.

On Mon, Oct 14, 2019 at 5:52 PM Christophe Fergeau
<notifications@github.com> wrote:
>
> Should this be closed as a duplicate of #13 ? Or do we keep this open to remember it would be useful to prioritize crc console?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by morningspace** [comment] 2020-02-11 10:34
Will this still be in the plan? @gbraad @cfergeau

**Comment by cfergeau** [comment] 2020-02-11 10:44
Not ruled out, but low priority.

**Comment by gbraad** [comment] 2020-07-17 09:19
Closing in favor of the discussion at #1227

**Closed by gbraad** 2020-07-17 09:19 UTC
Labels: status/pinned
