### ISSUE TITLE
[BUG] Failed to renew TLS certificates

### ISSUE THREAD

**Issue by Aenima4six2** [code-ready/crc#1273] opened 2020-06-01 23:46 UTC
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run Yes
  * Running CRC on: Laptop

## CRC version
```
crc version: 1.10.0+9025021
OpenShift version: 4.4.3 (embedded in binary)
```
  
## CRC status
```
DEBU Running '/Users/peej/.crc/bin/oc get co -ojson --kubeconfig /Users/peej/.crc/machines/crc/kubeconfig --context admin --cluster crc'
DEBU operator-lifecycle-manager-packageserver operator not available, Reason:
DEBU operator-lifecycle-manager-packageserver operator is still progressing, Reason:
DEBU About to run SSH command:
df -B1 --output=size,used,target /sysroot | tail -1
DEBU SSH cmd err, output: <nil>: 32719437824 9891975168 /sysroot
CRC VM:          Running
OpenShift:       Starting
Disk Usage:      9.892GB of 32.72GB (Inside the CRC VM)
Cache Usage:     12.05GB
Cache Directory: /Users/peej/.crc/cache
```

## CRC config
```
- cpus                                  : 6
- memory                                : 16384
- pull-secret-file                      : /Users/peej/openshift/pull-secret-file
```

## Host Operating System
```
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F96
```

### Steps to reproduce

```
crc delete -f
crc cleanup
crc setup
crc start --log-level debug
```

### Logs

[https://gist.github.com/Aenima4six2/f64c9298475babb621e78e74d8638fea](https://gist.github.com/Aenima4six2/f64c9298475babb621e78e74d8638fea)

**Comment by gbraad** [comment] 2020-06-02 02:44
Duplicate of https://github.com/code-ready/crc/issues/1242. We are aware of the issue and looking into this. A new release will be available soon to provide you with a working cluster with new certificates while we investigate why the renew process fails.

**Closed by gbraad** 2020-06-02 02:44 UTC
Labels: kind/bug
