### ISSUE TITLE
Alpha-2 (0.87.0): Cluster update in progress. Working towards 4.1.0: 97% complete

### ISSUE THREAD

**Issue by rbaumgar** [code-ready/crc#217] opened 2019-06-11 17:56 UTC
after starting crc cluster is not ready...
`Cluster update in progress. Working towards 4.1.0: 97% complete. View Cluster Operators for more details.`

```
machine-config
Degraded
4.1.0
Failed to resync 4.1.0 because: timed out waiting for the condition during syncRequiredMachineConfigPools: error pool master is not ready, retrying. Status: (pool degraded: true total: 1, ready 0, updated: 0, unavailable: 1)
  extension:
    master: 'pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node crc-4gdnp-master-0 is reporting: \"during bootstrap: unexpected on-disk state validating against rendered-master-c1cf9e56ad0184a7f97c5f94a177c0dc\""'
    worker: all 0 nodes are at latest configuration rendered-worker-fa978cf99801072b5703a6334e7cbe04
```
```
monitoring
Degraded
-
Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager Route to become ready failed: waiting for RouteReady of alertmanager-main: no status available for alertmanager-main
```

after 
`oc scale --replicas=1 dc/cluster-monitoring-operator -n openshift-monitoring`
monitoring is up and running

**Comment by rbaumgar** [comment] 2019-06-11 18:48
the ingress route should also scaled down by

`oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": 1}}' --type=merge`

**Comment by praveenkumar** [comment] 2019-06-12 02:50
@rbaumgar by default we scaled down `monitoring/marketplace/machineConfig` operators due to the resource bound. Specially monitoring takes a lot of resource since it run cluster level Prometheus.

This is by design for now, if a user really need and have enough resource on the system then they can scale it up and use.

**Comment by rbaumgar** [comment] 2019-06-12 07:40
ok, understood.
But it should be in a way, that the cluster should reach 100% complete... Otherwise it looks like something is wrong.

**Comment by rbaumgar** [comment] 2019-06-12 08:17
How can I enable the marketplace?

**Comment by praveenkumar** [comment] 2019-06-12 08:31
@rbaumgar `oc scale --replicas=1 deployment --all -n openshift-marketplace` should do it.

**Comment by praveenkumar** [comment] 2019-07-25 12:29
closing this one.

**Closed by praveenkumar** 2019-07-25 12:29 UTC
