### ISSUE TITLE
Add CI to create disk image

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#14] opened 2019-03-06 10:14 UTC
Disk image which is consumed by crc should have a CI in place and the scripts for this need to placed either in this repo or in a separate one.

**Comment by anjannath** [comment] 2019-04-17 06:48
Related to https://github.com/code-ready/crc/issues/53

**Comment by gbraad** [comment] 2019-04-17 07:40
Duplicate of #53

**Closed by gbraad** 2019-04-17 07:40 UTC
Labels: priority/critical, size/M
