### ISSUE TITLE
ssh keys

### ISSUE THREAD

**Issue by ckvtvm-arch** [code-ready/crc#1856] opened 2021-01-20 06:06 UTC
My organization has disabled generating ssh keys , hence the crc fails now. Please let me know how to manually handle this by copying the ssh keys to the crc folder.

### General information

  * OS:   macOS 
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?- yes

## CRC version
CodeReady Containers version: 1.19.0+94b0362

### Steps to reproduce

  1.  crc start

### Actual

 INFO Creating CodeReady Containers VM for OpenShift 4.6.3... 
Failed to connect to the CRC VM with SSH -- host might be unreachable: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
output  :  (x295)

**Comment by gbraad** [comment] 2021-01-20 06:39
@praveenkumar @guillaumerose Do we generate the certs using the hosts ssh tools?

**Comment by gbraad** [comment] 2021-01-20 06:40
Please provide a full startup output log. We need to understand what happened in previous steps.

**Comment by guillaumerose** [comment] 2021-01-20 08:22
We use go function to generate the ssh key. I believe the error is due to something else.

**Comment by gbraad** [comment] 2021-01-20 08:57
> We use go function to generate the ssh key

wanted to confirm this as I also believed so, as we would have no
access to those tools on Windows anyway.

> I believe the error is due to something else.

Full output log required.

On Wed, Jan 20, 2021 at 4:22 PM Guillaume Rose <notifications@github.com> wrote:
>
> We use go function to generate the ssh key. I believe the error is due to something else.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by cfergeau** [comment] 2021-01-20 11:28
Might be generation of RSA keys which is disabled, maybe 1.21 which uses ECDSA ssh keys would be better. If we really can't generate new keys, we could keep using the 'default' key which is part of the bundle.

**Comment by ckvtvm-arch** [comment] 2021-01-20 15:32
Yes, thats correct . I was able to generate ssh keys until the recent org policy change. Please let me know how i can keep the default ssh key as part of the bundle. My understanding is that the ssh keys will be generated in the folder @ /Users/af71194/.crc/machines/crc when we run crc start. I tried to copy my ssh key generated from the org security tool named venafi , but it removes those ssh keys once the crc starts.

**Comment by cfergeau** [comment] 2021-01-20 16:29
We still need the full debug log after a `crc delete; crc start --log-level debug` to get a better understanding of what is happening.

**Comment by cfergeau** [comment] 2021-01-20 16:29
1.21 was just released if you want to give it a try.

**Comment by ckvtvm-arch** [comment] 2021-01-20 17:06
af71194@LC02CHB58MD6R ~ % crc version
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
af71194@LC02CHB58MD6R ~ % crc delete; crc start --log-level debug
Do you want to delete the OpenShift cluster? [y/N]: y
Deleted the OpenShift cluster
DEBU CodeReady Containers version: 1.19.0+94b0362 
DEBU OpenShift version: 4.6.3 (embedded in executable) 
DEBU Total memory of system is 34359738368 bytes  
WARN A new version (1.21.0) has been published on https://cloud.redhat.com/openshift/install/crc/installer-provisioned 
INFO Checking if podman remote executable is cached 
DEBU Currently podman remote is not supported     
INFO Checking if goodhosts executable is cached   
DEBU goodhost executable already cached           
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 34359738368 bytes  
INFO Checking if running as non-root              
INFO Checking if HyperKit is installed            
DEBU Running '/Users/af71194/.crc/bin/hyperkit -v' 
DEBU Found hyperkit version v0.20200224-44-gb54460 
INFO Checking if crc-driver-hyperkit is installed 
DEBU Checking if crc-driver-hyperkit is installed 
DEBU Running '/Users/af71194/.crc/bin/crc-driver-hyperkit version' 
DEBU Found crc-driver-hyperkit version 0.12.10    
INFO Checking file permissions for /etc/hosts     
DEBU Checking if /etc/hosts ownership/permissions need to be adjusted after crc upgrade 
Checking file: /Users/af71194/.crc/machines/crc/.crc-exist
INFO Loading bundle: crc_hyperkit_4.6.3.crcbundle ... 
INFO Checking size of the disk image /Users/af71194/.crc/cache/crc_hyperkit_4.6.3/crc.qcow2 ... 
INFO Creating CodeReady Containers VM for OpenShift 4.6.3... 
Found binary path at /Users/af71194/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:52129
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(crc) Calling .GetMachineName
(crc) Calling .DriverName
Running pre-create checks...
(crc) Calling .PreCreateCheck
(crc) Calling .GetConfigRaw
Creating machine...
(crc) Calling .Create
(crc) DBG | clean start, hyperkit pid file doesn't exist: /Users/af71194/.crc/machines/crc/hyperkit.pid
(crc) DBG | Using hyperkit binary from /Users/af71194/.crc/bin/hyperkit
(crc) DBG | Starting with cmdline: BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-b0ce903752d15965417ddab65b8a8718e28ba8c1c0cf96b5764e8f1ba1b56503/vmlinuz-4.18.0-193.28.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/b0ce903752d15965417ddab65b8a8718e28ba8c1c0cf96b5764e8f1ba1b56503/0
(crc) DBG | Trying to execute /Users/af71194/.crc/bin/hyperkit -A -u -F /Users/af71194/.crc/machines/crc/hyperkit.pid -c 4 -m 9216M -s 0:0,hostbridge -s 31,lpc -U c3d68012-0208-11ea-9fd7-f2189899ab08 -s 1:0,virtio-blk,file:///Users/af71194/.crc/machines/crc/crc.qcow2,format=qcow -s 2,virtio-sock,guest_cid=3,path=/Users/af71194/.crc/machines/crc -s 3,virtio-rnd -l com1,autopty=/Users/af71194/.crc/machines/crc/tty,log=/Users/af71194/.crc/machines/crc/console-ring -f kexec,/Users/af71194/.crc/cache/crc_hyperkit_4.6.3/vmlinuz-4.18.0-193.28.1.el8_2.x86_64,/Users/af71194/.crc/cache/crc_hyperkit_4.6.3/initramfs-4.18.0-193.28.1.el8_2.x86_64.img,earlyprintk=serial BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-b0ce903752d15965417ddab65b8a8718e28ba8c1c0cf96b5764e8f1ba1b56503/vmlinuz-4.18.0-193.28.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/b0ce903752d15965417ddab65b8a8718e28ba8c1c0cf96b5764e8f1ba1b56503/0
(crc) Calling .GetConfigRaw
(crc) Calling .DriverName
(crc) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(crc) Calling .GetState
(crc) DBG | hyperkit pid from json: 87162
Machine is up and running!
Machine successfully created
Created /Users/af71194/.crc/machines/crc/.crc-exist
(crc) Calling .GetState
(crc) DBG | hyperkit pid from json: 87162
DEBU Waiting until ssh is available               
DEBU retry loop: attempt 0                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
output  :  - sleeping 1s 
DEBU retry loop: attempt 1                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
output  :  - sleeping 1s 
DEBU retry loop: attempt 2                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
output  :  - sleeping 1s 
DEBU retry loop: attempt 3                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
output  :  - sleeping 1s 
DEBU retry loop: attempt 4                        
DEBU About to run SSH command:
exit 0             
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by ckvtvm-arch** [comment] 2021-01-20 17:06
i can try 1.21 if ssh issue can be resolved

**Comment by cfergeau** [comment] 2021-01-20 17:13
This is the initial connection to the VM which is failing, which is using pre-created keys, so I don't think this is related to ssh key generation.

**Comment by ckvtvm-arch** [comment] 2021-01-21 00:44
Also i tried CRC 1.21 and still the same issue with slightly different description:

af71194@LC02CHB58MD6R ~ % crc delete; crc start --log-level debug
Do you want to delete the OpenShift cluster? [y/N]: y
Deleted the OpenShift cluster
DEBU CodeReady Containers version: 1.21.0+68a4cdd7 
DEBU OpenShift version: 4.6.9 (embedded in executable) 
DEBU Running 'crc start'                          
DEBU Total memory of system is 34359738368 bytes  
DEBU No new version available. The latest version is 1.21.0 
INFO Checking if running as non-root              
INFO Checking if podman remote executable is cached 
DEBU Currently podman remote is not supported     
INFO Checking if admin-helper executable is cached 
DEBU Running '/Users/af71194/.crc/bin/admin-helper-darwin --version' 
DEBU Found admin-helper-darwin version 0.0.2      
DEBU admin-helper executable already cached       
INFO Checking minimum RAM requirements            
DEBU Total memory of system is 34359738368 bytes  
INFO Checking if HyperKit is installed            
DEBU Running '/Users/af71194/.crc/bin/hyperkit -v' 
DEBU Found hyperkit version v0.20200224-44-gb54460 
INFO Checking if crc-driver-hyperkit is installed 
DEBU Checking if crc-driver-hyperkit is installed 
DEBU Running '/Users/af71194/.crc/bin/crc-driver-hyperkit version' 
DEBU Found crc-driver-hyperkit version 0.12.10    
INFO Checking file permissions for /etc/hosts     
DEBU Checking if /etc/hosts ownership/permissions need to be adjusted after crc upgrade 
Checking file: /Users/af71194/.crc/machines/crc/.crc-exist
INFO Loading bundle: crc_hyperkit_4.6.9.crcbundle ... 
INFO Verifying bundle crc_hyperkit_4.6.9.crcbundle ... 
INFO Creating CodeReady Containers VM for OpenShift 4.6.9... 
Found binary path at /Users/af71194/.crc/bin/crc-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:52044
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(crc) Calling .GetMachineName
(crc) Calling .DriverName
Running pre-create checks...
(crc) Calling .PreCreateCheck
(crc) Calling .GetConfigRaw
Creating machine...
(crc) Calling .Create
(crc) DBG | clean start, hyperkit pid file doesn't exist: /Users/af71194/.crc/machines/crc/hyperkit.pid
(crc) DBG | Using hyperkit binary from /Users/af71194/.crc/bin/hyperkit
(crc) DBG | Starting with cmdline: BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-a77c6a70e3037f40c6dc3634d31e63f797d4a5cf9059f5927141ca53690d1942/vmlinuz-4.18.0-193.37.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/a77c6a70e3037f40c6dc3634d31e63f797d4a5cf9059f5927141ca53690d1942/0
(crc) DBG | Trying to execute /Users/af71194/.crc/bin/hyperkit -A -u -F /Users/af71194/.crc/machines/crc/hyperkit.pid -c 4 -m 9216M -s 0:0,hostbridge -s 31,lpc -U c3d68012-0208-11ea-9fd7-f2189899ab08 -s 1:0,virtio-blk,file:///Users/af71194/.crc/machines/crc/crc.qcow2,format=qcow -s 2,virtio-sock,guest_cid=3,path=/Users/af71194/.crc/machines/crc -s 3,virtio-rnd -l com1,autopty=/Users/af71194/.crc/machines/crc/tty,log=/Users/af71194/.crc/machines/crc/console-ring -f kexec,/Users/af71194/.crc/cache/crc_hyperkit_4.6.9/vmlinuz-4.18.0-193.37.1.el8_2.x86_64,/Users/af71194/.crc/cache/crc_hyperkit_4.6.9/initramfs-4.18.0-193.37.1.el8_2.x86_64.img,earlyprintk=serial BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-a77c6a70e3037f40c6dc3634d31e63f797d4a5cf9059f5927141ca53690d1942/vmlinuz-4.18.0-193.37.1.el8_2.x86_64 rhcos.root=crypt_rootfs random.trust_cpu=on console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu rd.luks.options=discard ostree=/ostree/boot.1/rhcos/a77c6a70e3037f40c6dc3634d31e63f797d4a5cf9059f5927141ca53690d1942/0
(crc) Calling .GetConfigRaw
(crc) Calling .DriverName
(crc) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(crc) Calling .GetState
(crc) DBG | hyperkit pid from json: 20919
Machine is up and running!
Machine successfully created
Created /Users/af71194/.crc/machines/crc/.crc-exist
(crc) Calling .GetState
(crc) DBG | hyperkit pid from json: 20919
DEBU Waiting until ssh is available               
DEBU retry loop: attempt 0                        
DEBU About to run SSH command:
exit 0             
Cannot read private ssh key /Users/af71194/.crc/machines/crc/id_ecdsa
Cannot read private ssh key /Users/af71194/.crc/machines/crc/id_rsa
DEBU SSH command results: err: dial tcp 127.0.0.1:2222: connect: connection refused, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : dial tcp 127.0.0.1:2222: connect: connection refused\n - sleeping 1s 
DEBU retry loop: attempt 1                        
DEBU About to run SSH command:
exit 0             
Cannot read private ssh key /Users/af71194/.crc/machines/crc/id_ecdsa
Cannot read private ssh key /Users/af71194/.crc/machines/crc/id_rsa
DEBU SSH command results: err: dial tcp 127.0.0.1:2222: connect: connection refused, output:  
DEBU error: Temporary error: ssh command error:
command : exit 0

**Comment by ckvtvm-arch** [comment] 2021-01-21 00:44
Is it something to do with my ssh key policy in my organization ?

**Comment by rhtevan** [comment] 2021-01-21 00:59
I was facing the same issue on Fedora 33. Got some clue from this blog (https://dev.to/bowmanjd/upgrade-ssh-client-keys-and-remote-servers-after-fedora-33-s-new-crypto-policy-47ag), and then downgraded security, `update-crypto-policies --set LEGACY` followed by a reboot. ISSUE RESOLVED! 

Now, the missing keys appear. 

└── machines
    └── crc
        ├── config.json
        ├── crc.qcow2
        ├── id_ecdsa
        ├── id_ecdsa.pub
        └── kubeconfig

**Comment by ckvtvm-arch** [comment] 2021-01-21 01:14
thanks , may i please know how i run update crypto policy from my Mac OS , i am doing some google now.

**Comment by gbraad** [comment] 2021-01-21 03:42
> DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:  

Right. I see the same ... the key pivoting is not even occuring yet.

What is enforcing this policy? Is there a tool on the machine that captures SSH sessions and keys?

**Comment by guillaumerose** [comment] 2021-01-21 08:51
We use the Golang ssh client. I don't see how `update-crypto-policies --set LEGACY` can solve this. :thinking:

**Comment by cfergeau** [comment] 2021-01-21 17:34
@ckvtvm-arch  is the `crc daemon` running? I see that you are using `network-mode vsock`, which requires this daemon to run for networking, so I prefer to make sure it's actually running :)

**Comment by ckvtvm-arch** [comment] 2021-01-21 20:30
Yes, crc daemon is running. but the ssh keys are not getting generated due to some security policy. let me ask the security architect in my meeting tomorrow

**Comment by ckvtvm-arch** [comment] 2021-01-22 03:05
somehow it started working now. i am closing it now..

**Comment by gbraad** [comment] 2021-01-25 09:28
> Yes, crc daemon is running. but the ssh keys are not getting generated due to some security policy.

I highly doubt this is caused by a company policy as our code would be unaware of this, unless low-level inspection would be performed. This might have been an edge case where the VM was started, but the key pivot did not get performed properly, but a restart expects this to be present?

Anyway ... more information would have been needed but got closed before this. Marking as invalid

**Comment by ckvtvm-arch** [comment] 2021-01-25 22:58
sorry

**Comment by gbraad** [comment] 2021-01-26 02:46
> But it looks like crc is able to bypass the security policy. if i try to sshgen , i get a message saying that ssh keys cannot be generated and i have to generate the keys via venafi !

not sure what the resoltuion is in that case. You say CRC can bypass but you need to generate keys yourself? If so, you placed them manually in the ~/,crc/machines folder?

if our code fals to generate the keys it wil fail very hard and there is no way to recover this.

**Comment by gbraad** [comment] 2021-01-26 02:48
we have been able to repro the scenario, with the same error message, when the `vsock` network method is used and the `daemon` wasn't running. As this will prevent CRC from being able to communicate and start the initial key rotation,

**Comment by ckvtvm-arch** [comment] 2021-01-26 03:05
I cannot create ssh keys from my organization laptop, but my question was how CRC is able to create it with the security policy in place. Anyway i believe that the issue was may be due to the daemon not running as you pointed out as i frequently experience network issues.

**Closed** 2021-02-15 23:24 UTC
Labels: resolution/invalid
