### ISSUE TITLE
Running CRC on macOS mojave failed

### ISSUE THREAD

**Issue by phracek** [code-ready/crc#454] opened 2019-08-23 06:42 UTC
I am trying to run OpenShift 4 on my macOS Mojave, but it seems, like
CRC bundle is not included in version `0.90.0-alpha5-4.1.9`
I have downloaded it from the release page.

The output from `crc setup` looks like this:
```bash
sh# $HOME/crc-0.90.0-alpha-darwin-amd64/crc setup
INFO Caching oc binary
INFO Setting up virtualization with HyperKit
INFO Installing crc-machine-hyperkit
INFO Setting file permissions for /etc/resolver/testing
INFO Setting file permissions for /etc/hosts
INFO Unpacking bundle from the CRC binary
WARN CRC bundle is not embedded in the binary, see 'crc help' for more details.
```
The output from CRC start looks like this
```bash
sh# $HOME/crc-0.90.0-alpha-darwin-amd64/crc start
ERRO Error occurred: File /Users/phracek/.crc/crc_hyperkit_4.1.9.crcbundle does not exist
ERRO Error occurred: Run 'crc setup' to unpack the bundle to disk.
```

My Playbook repository is here:
https://github.com/phracek/openshift4-crc

Any idea, what's going wrong?

**Comment by phracek** [comment] 2019-08-23 06:49
My this is a dup of https://github.com/code-ready/crc/issues/429

**Comment by praveenkumar** [comment] 2019-08-23 06:54
@phracek you don't need any ansible playbook to set the pre-requisites to use the `crc` basically `crc setup` should do it for you (if not then it is the bug from our end) and the `crc start`

**Comment by phracek** [comment] 2019-08-23 07:11
I see, and where can I download `crc_hyperkit_4.1.9.crcbundle`?
I did not find any link or docu.
Thanks for the help.

**Comment by gbraad** [comment] 2019-08-23 07:16
Duplicate of #263

**Closed by gbraad** 2019-08-23 07:16 UTC
