### ISSUE TITLE
[BUG] removal of automated virtual box setup on macos

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#581] opened 2019-09-12 00:23 UTC
This is unmaintained and unsupported code. When removed it also eliminates the need for us handling root/admin privileges needs on setup. The user is responsible for setting this up (as in most corporate environments this comes preinstalled)

**Comment by cfergeau** [comment] 2019-11-06 11:45
Duplicate of #662

**Closed by cfergeau** 2019-11-06 11:45 UTC
Labels: kind/bug
