### ISSUE TITLE
Why is crc restarting all my networks on macOS?

### ISSUE THREAD

**Issue by kadel** [code-ready/crc#797] opened 2019-11-08 13:17 UTC
I'm running crc on Mac. 
Each time I start CRC it restarts all my networks. 
This is a little bit annoying as it interrupts other work that I'm doing at the same time :-(

Is there a way to start crc without disconnecting me from the internet?

**Comment by cfergeau** [comment] 2019-11-08 13:37
It should only be doing that after a 'crc delete && crc start' cycle, not on 'crc stop && crc start'. Are you seeing the network restart more often than that? We haven't figured out yet a better way of triggering a reload of `/etc/resolver/testing`

**Comment by kadel** [comment] 2019-11-11 11:44
You are right, I've been running `crc delete && crc start` quite a lot as I was testing something where I always needed a fresh cluster.

**Comment by cfergeau** [comment] 2019-11-12 09:45
Issue #798 could be a way around this problem to minimize even more the number of network restarts.

**Comment by gbraad** [comment] 2019-11-12 10:50
#798 might move this to the setup phase, but a restart (once) is at least needed

**Comment by cfergeau** [comment] 2019-12-17 08:39
Duplicate of #322

**Closed by cfergeau** 2019-12-17 08:39 UTC
Labels: kind/question, os/macos, priority/minor
