### ISSUE TITLE
libvirt check segfaults

### ISSUE THREAD

**Issue by radekvokal** [code-ready/crc#157] opened 2019-05-23 11:50 UTC
crc 0.86.0 - when started with libvirt enables but user not in libvirt group the following crash happens

```
./crc start
crc - Local OpenShift 4.x cluster
INFO  Checking if Virtualization is enabled       
INFO  Checking if KVM is enabled                  
INFO  Checking if Libvirt is installed            
INFO  Checking if user is part of libvirt group   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x908b31]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/preflight.preflightCheckSucceedsOrFails(0xc0001ac600, 0xa5eaf0, 0xa4bb51, 0x29, 0x0)
        /home/prkumar/work/github/crc/pkg/crc/preflight/preflight_common.go:26 +0x171
github.com/code-ready/crc/pkg/crc/preflight.StartPreflightChecks()
        /home/prkumar/work/github/crc/pkg/crc/preflight/preflight_linux.go:25 +0x269
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xf34bd8, 0x0, 0x0)
        /home/prkumar/work/github/crc/cmd/crc/cmd/start.go:44 +0x4e
github.com/code-ready/crc/cmd/crc/cmd.glob..func6(0xf0e1e0, 0xf34bd8, 0x0, 0x0)
        /home/prkumar/work/github/crc/cmd/crc/cmd/start.go:30 +0x3f
github.com/spf13/cobra.(*Command).execute(0xf0e1e0, 0xf34bd8, 0x0, 0x0, 0xf0e1e0, 0xf34bd8)
        /home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xf0dd20, 0x40748f, 0xc00009c058, 0x0)
        /home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/code-ready/crc/cmd/crc/cmd.Execute()
        /home/prkumar/work/github/crc/cmd/crc/cmd/root.go:57 +0x2e
main.main()
        /home/prkumar/work/github/crc/cmd/crc/main.go:10 +0x25
```

**Comment by anjannath** [comment] 2019-05-24 08:30
Duplicate of #110

**Closed by anjannath** 2019-05-24 08:30 UTC
