### ISSUE TITLE
dns doesn't work for routes

### ISSUE THREAD

**Issue by tmds** [code-ready/crc#1729] opened 2020-11-30 08:10 UTC
I've just installed `crc` on Fedora 33.
```
$ crc version
CodeReady Containers version: 1.19.0+94b0362
OpenShift version: 4.6.3 (embedded in executable)
```

I've added the dotnet sample application which creates a route:

```
$ oc get route
NAME            HOST/PORT                                   PATH   SERVICES        PORT       TERMINATION   WILDCARD
dotnet-sample   dotnet-sample-dotnetdemo.apps-crc.testing          dotnet-sample   8080-tcp                 None
```

Browsing to `dotnet-sample-dotnetdemo.apps-crc.testing` doesn't work.
The DNS fails to resolve this name.

To verify it is a DNS an issue, I've manually edited `/etc/hosts`, and added this last line:
```
192.168.130.11 default-route-openshift-image-registry.apps-crc.testing api.crc.testing oauth-openshift.apps-crc.testing console-openshift-console.apps-crc.testing
192.168.130.11 dotnet-sample-dotnetdemo.apps-crc.testing
```
Now I can browse to the website.

**Comment by cfergeau** [comment] 2020-11-30 08:13
fedora33 support is being worked on https://github.com/code-ready/crc/issues/1624

**Comment by cfergeau** [comment] 2020-11-30 08:14
Duplicate of #1572

**Comment by gbraad** [comment] 2020-11-30 09:06
If duplicated we close the new issue

**Closed by gbraad** 2020-11-30 09:06 UTC
Labels: kind/bug
