### ISSUE TITLE
Add preflight check for availability of HyperV and dependent cmdlets on Powershell Core (v6)

### ISSUE THREAD

**Issue by tofflos** [code-ready/crc#616] opened 2019-09-19 18:40 UTC
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```Powershell
PS C:\Users\Erik> crc version
version: 1.0.0-beta.5+f2aa58c
OpenShift version: 4.1.14 (embedded in binary)
```
 
## CRC status
```bash
# Put `crc status` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. Run crc start in Windows Terminal (Preview) / Powershell 6.1.1
  2. 
  3. 
  4. 

### Expected
I then closed the Windows Terminal and tried again in regular PowerShell version 5.1 and had no problems. I expect it to work like that. I'm unsure whether it's the new terminal or the newer version of PowerShell 6.1.1 that's causing the issue.

### Logs

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
```Powershell
PowerShell 6.1.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\Erik> crc setup
INFO Checking if running as normal user
INFO Caching oc binary
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
INFO Hyper-V installed
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
Setup is complete, you can now run 'crc start' to start a CodeReady Containers instance
```
```Powershell
PS C:\Users\Erik> crc start --log-level debug
INFO Checking if running as normal user
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
Checking file: C:\Users\Erik\.crc\machines\crc\.crc-exist
? Image pull secret [? for help] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
INFO Loading bundle: crc_hyperv_4.1.14.crcbundle ...
INFO Creating VM ...
Found binary path at C:\Program Files\crc-windows-1.0.0-beta.5-amd64\crc.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:50954
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(crc) Calling .GetMachineName
(crc) Calling .DriverName
Running pre-create checks...
(crc) Calling .PreCreateCheck
(crc) DBG | [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique (crc) DBG | [stdout =====>] :
(crc) DBG | [stderr =====>] : Get-Unique : The 'Get-Unique' command was found in the module 'Microsoft.PowerShell.Utility', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Utility'. (crc) DBG | At line:1 char:45
(crc) DBG | + @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
(crc) DBG | + ~~~~~~~~~~
(crc) DBG | + CategoryInfo : ObjectNotFound: (Get-Unique:String) [], CommandNotFoundException
(crc) DBG | + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
(crc) DBG |
 (crc) DBG |
 ERRO Error occurred: Error creating host: Error creating the VM. Error with pre-create check: "exit status 1"
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
(crc) DBG | Closing plugin on server side
Making call to close connection to plugin binary
```

**Comment by gbraad** [comment] 2019-09-20 02:53
you need to load the Hyper-V cmdlets before they can be used. PowerShell Core does not include them automagically on startup.

We might want to add a preflight check for this, but this is not an issue with CRC.

**Comment by gbraad** [comment] 2019-09-20 02:58
```ps
PS> Import-Module C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\Hyper-V\2.0.0.0\Hyper-V.psd1
PS> Import-Module Microsoft.PowerShell.Utility
```

**Comment by gbraad** [comment] 2019-09-25 06:40
@tofflos can you run `(Get-Command -Module Microsoft.Powershell.Utility).Name` inside your PowerShell 6.1.1 environment?

**Comment by gbraad** [comment] 2019-09-25 06:54
I am inclined to close this as `Get-Unique` is supposed to be part of the standard set of cmdlets for any PowerShell. Even if this cmdlet is not available, module auto-loading should kick in and reload this module.

Adding a check for Hyper-V cmdlets might be possible, but even those should be available, as we already check for the existence of the Hyper-V feature.

Adding a check for `Get-Unique` is like testing if the Command Prompt offers `dir`. It should work... this most likely is therefore an issue on the users end related to his setup. More info is needed.

**Comment by gbraad** [comment] 2019-09-25 07:03
https://github.com/code-ready/crc/blob/9a47ead42397c6ed2f59238168391329828497aa/pkg/crc/preflight/preflight_checks_windows.go#L45

We could add the check to see if the client tools are installed, but then again... this is implied with our fix function and the reported issue was for a standard cmdlet being missing.

**Comment by tofflos** [comment] 2019-09-28 08:52
> 
> 
> @tofflos can you run `(Get-Command -Module Microsoft.Powershell.Utility).Name` inside your PowerShell 6.1.1 environment?

```Powershell
PS C:\Users\Erik> (Get-Command -Module Microsoft.Powershell.Utility).Name
ConvertFrom-SddlString
Add-Member
Add-Type
Clear-Variable
Compare-Object
ConvertFrom-Csv
ConvertFrom-Json
ConvertFrom-Markdown
ConvertFrom-StringData
ConvertTo-Csv
ConvertTo-Html
ConvertTo-Json
ConvertTo-Xml
Debug-Runspace
Disable-PSBreakpoint
Disable-RunspaceDebug
Enable-PSBreakpoint
Enable-RunspaceDebug
Export-Alias
Export-Clixml
Export-Csv
Export-FormatData
Export-PSSession
Format-Custom
Format-Hex
Format-List
Format-Table
Format-Wide
Get-Alias
Get-Culture
Get-Date
Get-Event
Get-EventSubscriber
Get-FileHash
Get-FormatData
Get-Host
Get-MarkdownOption
Get-Member
Get-PSBreakpoint
Get-PSCallStack
Get-Random
Get-Runspace
Get-RunspaceDebug
Get-TraceSource
Get-TypeData
Get-UICulture
Get-Unique
Get-Uptime
Get-Variable
Get-Verb
Group-Object
Import-Alias
Import-Clixml
Import-Csv
Import-LocalizedData
Import-PowerShellDataFile
Import-PSSession
Invoke-Expression
Invoke-RestMethod
Invoke-WebRequest
Measure-Command
Measure-Object
New-Alias
New-Event
New-Guid
New-Object
New-TemporaryFile
New-TimeSpan
New-Variable
Out-File
Out-String
Read-Host
Register-EngineEvent
Register-ObjectEvent
Remove-Alias
Remove-Event
Remove-PSBreakpoint
Remove-TypeData
Remove-Variable
Select-Object
Select-String
Select-Xml
Send-MailMessage
Set-Alias
Set-Date
Set-MarkdownOption
Set-PSBreakpoint
Set-TraceSource
Set-Variable
Show-Markdown
Sort-Object
Start-Sleep
Tee-Object
Test-Json
Trace-Command
Unblock-File
Unregister-Event
Update-FormatData
Update-TypeData
Wait-Debugger
Wait-Event
Write-Debug
Write-Error
Write-Host
Write-Information
Write-Output
Write-Progress
Write-Warning
Write-Verbose
```

**Comment by gbraad** [comment] 2019-09-28 10:06
I am unable to reproduce this with PowerShell core 6.0.0 (first release) and the current latest.

> Get-Unique

the cmdlet exists, so there is something wrong with your setup.
Will mark this issue as invalid. If you believe this is wrong, please re-open and provide more information about your setup.

**Closed by gbraad** 2019-09-28 10:06 UTC
Labels: kind/enhancement, os/windows, priority/minor, state/need more information
