### ISSUE TITLE
running out of disk quickly with default 32GB

### ISSUE THREAD

**Issue by csantanapr** [code-ready/crc#1608] opened 2020-10-21 02:13 UTC
**How do I create a VM with larger disk space?** I didn't find an option under `crc config` or `crc start`

### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: Laptop 

## CRC version
```bash
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.5.14)
Disk Usage:      26.11GB of 32.72GB (Inside the CRC VM)
Cache Usage:     13.2GB
Cache Directory: /Users/$USER/.crc/cache
```

`oc debug node/`
```
df -h
Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/coreos-luks-root-nocrypt   31G   25G  6.4G  80% /
tmpfs                                 9.8G     0  9.8G   0% /sys/fs/cgroup
devtmpfs                              9.8G     0  9.8G   0% /dev
tmpfs                                 9.8G  168K  9.8G   1% /dev/shm
tmpfs                                 9.8G   16M  9.8G   1% /run
```

## CRC config
```bash
- cpus                                  : 6
- memory                                : 20384
```

### Steps to reproduce

  1.  crc setup
  2.  crc start
  3.  install openshift pipelines
  4.  run a few builds ~5 using buildah

### Expected

Not run out of disk space so fast

### Actual

Ran out of disk space on the VM

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment] 2020-10-21 03:38
> How do I create a VM with larger disk space? I didn't find an option under crc config or crc start

You cannot do it with current crc releases, but there's a PR for disk resize feature (https://github.com/code-ready/crc/pull/1607) should be part of the next release.

**Comment by gbraad** [comment] 2020-10-21 05:12
Closing as this is a duplicate of previous issues, including #127 to resolve this.
An upcoming release will resolve this.

**Closed by gbraad** 2020-10-21 05:12 UTC
Labels: kind/enhancement
