### ISSUE TITLE
On windows 10, crc start fails if it is installed on different drive than Users

### ISSUE THREAD

**Issue by dinolupo** [code-ready/crc#912] opened 2019-12-26 12:25 UTC
# General information

If crc.exe is installed on `D:` and Users is on `C:` the setup command goes fine, but the start gives an error. 

# Expected
Start must work.

In fact, setup went ok installing `.crc` in home directory:

> listing cache in home directory

```txt
PS D:\bin\OpenShiftCodeReady-1.3.0> dir C:\Users\dinol\.crc\cache\

    Directory: C:\Users\dinol\.crc\cache

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        26/12/2019     12:17                crc_hyperv_4.2.10
-a----        26/12/2019     11:44     2423108152 crc_hyperv_4.2.10.crcbundle
``` 

# Actual
> running the start command from D:

```txt
PS D:\bin\OpenShiftCodeReady-1.3.0> dir

    Directory: D:\bin\OpenShiftCodeReady-1.3.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        17/12/2019     12:52     2435434182 crc.exe
-a----        17/12/2019     12:52         213524 doc.pdf
-a----        17/12/2019     12:52          11325 LICENSE

PS D:\bin\OpenShiftCodeReady-1.3.0> .\crc start
INFO Checking if running as normal user
INFO Checking if oc binary is cached
INFO Check Windows 10 release
INFO Hyper-V installed and operational
INFO Is user a member of the Hyper-V Administrators group
INFO Does the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
? Image pull secret [? for help] ***...***

INFO Loading bundle: crc_hyperv_4.2.10.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.10...
ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: open /Users/dinol/.crc/cache/crc_hyperv_4.2.10/crc.vhdx: The system cannot find the path specified.
```

# Additional

`winver`: Windows version 2004 (OS Build 1904.1)
CodeReady version: 1.3.0

**Comment by gbraad** [comment] 2019-12-26 14:27
Known issue as described in the Release Notes and duplicate of: #764

**Closed by gbraad** 2019-12-26 14:27 UTC
