### ISSUE TITLE
Please make storage configurable

### ISSUE THREAD

**Issue by jeffsaremi** [code-ready/crc#1105] opened 2020-03-14 04:48 UTC
### General information

  * OS: Windows
  * Hypervisor: Hyper-V

This is an enhancement request to make disk size a configuration parameter similar to memory and cpu.

Currently, I have to do `crc setup` plus `crc start`, and once done,
  do `crc stop`, 
  increase size of virtual disk, 
  do `crc start` , 
  ssh into the VM and expand sysroot.

If I had a config parameter I would have to do all that

**Comment by gbraad** [comment] 2020-03-14 05:13
As explained in https://github.com/code-ready/crc/issues/1075#issuecomment-596075478 we can not parameterize this part as this would affect ther startup of all users. You can however create a script yourself that targets the CRC node and performs actions with `ssh`.

**Comment by gbraad** [comment] 2020-03-14 05:14
Duplicate of #127

**Closed by gbraad** 2020-03-14 05:14 UTC
