### ISSUE TITLE
CRC bundle is not embedded in the binary

### ISSUE THREAD

**Issue by cmoulliard** [code-ready/crc#468] opened 2019-08-26 10:03 UTC
## Issue

On mac oc using latest CRC release, we get such error. So, how can we download the bundle as mentioned ? Is it documented ?

```
./Downloads/crc-0.90.0-alpha-darwin-amd64/crc start
ERRO Error occurred: File /Users/dabou/.crc/crc_hyperkit_4.1.9.crcbundle does not exist
ERRO Error occurred: Run 'crc setup' to unpack the bundle to disk.

./Downloads/crc-0.90.0-alpha-darwin-amd64/crc setup
INFO Caching oc binary
INFO Setting up virtualization with HyperKit
Password:
INFO Installing crc-machine-hyperkit
INFO Setting file permissions for /etc/resolver/testing
INFO Setting file permissions for /etc/hosts
INFO Unpacking bundle from the CRC binary
WARN CRC bundle is not embedded in the binary, see 'crc help' for more details.

./Downloads/crc-0.90.0-alpha-darwin-amd64/crc start
ERRO Error occurred: File /Users/dabou/.crc/crc_hyperkit_4.1.9.crcbundle does not exist
ERRO Error occurred: Run 'crc setup' to unpack the bundle to disk.
```

**Comment by gbraad** [comment] 2019-08-26 11:22
duplicate of #263
We haven't released yet so we can not embed the bundle just yet

**Comment by gbraad** [comment] 2019-08-26 11:33
Keep an eye on https://github.com/code-ready/crc/releases/tag/1.0.0-beta.1

**Closed by gbraad** 2019-08-26 11:33 UTC
