### ISSUE TITLE
[BUG] Failure to setup CRC on Windows 10

### ISSUE THREAD

**Issue by DhruvM1994** [code-ready/crc#752] opened 2019-10-22 07:45 UTC
### General information

  * OS: Windows 10 (1809)
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes)?

## CRC version
```bash
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831
```
  

## CRC config
```bash
skip-check-windows-version            : true
```

### Steps to reproduce

  1. Download above version of crc and run "crc setup"

### Expected
Setup should succeed

### Actual
When executing crc setup the following errors occur:
-Failed to get Windows release id
-Please manually update your Windows 10 installation
-Please manually update your Windows 10 installation

When skipping the windows version check the following errors occur:
-Hyper-V not installed

However, the os is updated and Hyper-V is installed.

**Comment by anjannath** [comment] 2019-10-22 09:23
@DhruvM1994 I couldn't reproduce the issue, tried on a Windows 10 (1803).

The setup command tries to fix the error, in your case when it found out that Hyper-V is not enabled, `crc setup` will try to enable it.

Please provide the following o/p:
```posh
Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId
```

Also put the full o/p from setup command? run with debug logs enabled `crc setup --log-level debug`

**Comment by DhruvM1994** [comment] 2019-10-22 09:33
It seems that crc cannot not find the location of the Hyper-V installation. I am also wondering why it cannot find the Windows release id.

Output of ```Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId``` is:
```
ReleaseId    : 1809
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT
PSChildName  : CurrentVersion
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

Output of ```crc setup --log-level debug``` is:
```
INFO Checking if running as normal user
INFO Caching oc binary
DEBU oc binary already cached
INFO Unpacking bundle from the CRC binary
INFO Check Windows 10 release
ERRO Error occurred: Failed to get Windows release id
DEBU Failed to get Windows release id
ERRO Error occurred: Please manually update your Windows 10 installation
FATA Please manually update your Windows 10 installation
```

**Comment by gbraad** [comment] 2019-10-22 09:45
This might happen when the path of the PowerShell command is incorrect (not on path?). As this is the first instance of using PowerShell

**Comment by DhruvM1994** [comment] 2019-10-22 09:57
The path to poweshell is there and it seems to be correct. But when I try executing ```powershell```in the command-line it says ```Access denied```

**Comment by DhruvM1994** [comment] 2019-10-22 10:07
You were right with the path to powershell. 
I had additionally an invalid path (C:\Windows\System32) to powershell.

Thank you very much.

**Comment by anjannath** [comment] 2019-10-22 10:13
@DhruvM1994 So you are able to use `crc` now? Feel free to close this issue if that is the case.

**Comment by gbraad** [comment] 2019-10-22 10:22
I believe we can improve this.

We check for the location of PowerShell, but fail with an error... perhaps we can expose this.
But we can also, on first error to locate in path, use the default location before failing completely.

**Closed** 2019-10-22 13:25 UTC
Labels: kind/bug, state/need more information
