### ISSUE TITLE
Error creating the VM: "System cannot find the path specified" during start

### ISSUE THREAD

**Issue by adrianpowell** [code-ready/crc#913] opened 2019-12-26 23:14 UTC
I'm using Windows 10 and trying to start CRC as `crc start`. It goes through the process to enter the pull secret then I get:
```
INFO Loading bundle: crc_hyperv_4.2.10.crcbundle ...
INFO Creating CodeReady Containers VM for OpenShift 4.2.10...
ERRO Error creating host: Error creating the VM: Error creating machine: Error in driver during machine creation: open /Users/powel/.crc/cache/crc_hyperv_4.2.10/crc.vhdx: The system cannot find the path specified.
```
I have tried deleting the folder `C:\Users\powel\.crc` and re-running the `crc setup` and `crc start` but I get the same error. It looks like for whatever reason some file is dropping the "c:/" prefix for my home directory and failing. Are there work arounds?

**Comment by gbraad** [comment] 2019-12-27 11:49
Duplicate of #912, #764 
make sure you have the executable on `C:\`. 

Let me know if this helped.

**Closed by gbraad** 2019-12-27 11:49 UTC
