### ISSUE TITLE
Possible to run 2 crc instances parallel on same host?

### ISSUE THREAD

**Issue by disposab1e** [code-ready/crc#1250] opened 2020-05-24 08:53 UTC
Is it possible to run two crc instances paralle on one host?

**Comment by disposab1e** [comment] 2020-05-24 08:59
Primarly with Centos 8.1...

**Comment by gbraad** [comment] 2020-05-25 07:27
Technically possible, but not on our todolist as this will cause harm due to conflicts with domain names, resource usage, etc. Duplicate of earlier issue, closing as such

**Closed by gbraad** 2020-05-25 07:27 UTC

**Comment by gbraad** [comment] 2020-05-25 07:31
Duplicate of #935
