### ISSUE TITLE
crc setup keeps asking for a reboot

### ISSUE THREAD

**Issue by mjgkaastrupandersen** [code-ready/crc#2466] opened 2021-06-21 22:34 UTC
Something seems off about the user/group management part of the crc setup. 
I have 
- run `crc delete`
- run `crc cleanup`
- deleted the .crc folder
- deleted the crc-users group 
- Removed and reinstalled Hyper-V
- Restarted once every 5 minutes my entire workday yesterday

but it makes no difference. I keep getting this message, when running `crc setup`:

```
crc-windows-1.28.0-amd64> .\crc.exe setup --log-level debug
DEBU CodeReady Containers version: 1.28.0+08de64bd
DEBU OpenShift version: 4.7.13 (embedded in executable)
DEBU Running 'crc setup'
INFO Checking if crc-admin-helper executable is cached
DEBU Running 'C:\Users\<<local_user>>\.crc\bin\crc-admin-helper-windows.exe --version'
DEBU Found crc-admin-helper-windows.exe version 0.0.6
DEBU crc-admin-helper executable already cached
INFO Checking for obsolete admin-helper executable
DEBU Checking if an older admin-helper executable is installed
DEBU No older admin-helper executable found
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
DEBU Total memory of system is 34122080256 bytes
INFO Checking if running in a shell with administrator rights
DEBU Running '$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent());$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)'
INFO Checking Windows 10 release
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
INFO Checking Windows edition
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
DEBU Running on Windows Professional edition
INFO Checking if Hyper-V is installed and operational
DEBU Running '@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent'
DEBU Running '@(Get-Service vmms).Status'
INFO Checking if crc-users group exists
DEBU Running 'Get-LocalGroup -Name crc-users'
INFO Checking if current user is in Hyper-V group and crc-users group
DEBU Running 'Get-LocalGroupMember -Name crc-users -Member '<<local_user>>''
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-LocalGroupMember : Principal <<local_user>> was not found.
At line:1 char:43
+ ... yContinue'; Get-LocalGroupMember -Name crc-users -Member '<<local_user>> ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (<<local_user>>:String) [Get-LocalGroupMember], PrincipalNotFoundExc
   eption
    + FullyQualifiedErrorId : PrincipalNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

DEBU exit status 1
INFO Adding current user to group
DEBU Running 'Get-LocalGroupMember -Name crc-users -Member '<<local_user>>''
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-LocalGroupMember : Principal <<local_user>> was not found.
At line:1 char:43
+ ... yContinue'; Get-LocalGroupMember -Name crc-users -Member '<<local_user>> ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (<<local_user>>:String) [Get-LocalGroupMember], PrincipalNotFoundExc
   eption
    + FullyQualifiedErrorId : PrincipalNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

INFO Will run as admin: adding current user to crc-users group
DEBU Running 'C:\Users\<<local_user>>\AppData\Local\Temp\crcScripts970071379\runAsAdmin.ps1'
DEBU Running '$sid = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-32-578")
        @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole($sid)'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
Please reboot your system and run 'crc setup' to complete the setup process
```

Note that I have replaced my actual username with <<local_user>>.

Let me know, if you need additional info .

**Comment by gbraad** [comment] 2021-06-22 03:56
was the user part of the `crc-users` group and/or `hyper-v administrators` group? Please use the OS tools to verify this.
Also, what was the actual process before you resorted to a deletion and removal process?

```
$ crc setup
<reboot>
$ ...
```

**Comment by gbraad** [comment] 2021-06-22 04:10
Duplicate of https://github.com/code-ready/crc/issues/2446

**Closed by gbraad** 2021-06-22 04:10 UTC
Labels: os/windows, status/need more information

**Comment by mjgkaastrupandersen** [comment] 2021-06-22 05:51
> was the user part of the `crc-users` group and/or `hyper-v administrators` group? Please use the OS tools to verify this.

Yes, my domain user `AzureAD\<local_user>` was part of both groups.

> Also, what was the actual process before you resorted to a deletion and removal process?

> ```
> $ crc setup
> <reboot>
> $ ...
> ```

Yes. I have done this several times. Also this worked fine until, as far as I remember, 1.27. Actually I'm quite sure i got 1.28 up and running last friday (3-4 days ago) but I'm not entirely sure.

> Note: sicne you didn't follow the template, essential information is missing. Please indicate if this machine is part of a domain.

I apologize. I did not know there was a template but yes, the user is part of a domain called AzureAD.

**Comment by mjgkaastrupandersen** [comment] 2021-06-22 05:55
For anyone finding this at a later point, this one fixed it for me: 
https://github.com/code-ready/crc/issues/2446#issuecomment-865028602

**Comment by gbraad** [comment] 2021-06-22 06:15
Recent versions introduced a crc-users group to handle the permissions for the daemon; to allow it creating creates the routes, hosts using the user mode network stack. It seems some issues exist when dealing with a domain joined machine.
