### ISSUE TITLE
Add a troubleshooting section in the documents

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#494] opened 2019-08-28 13:36 UTC
This is something recently @veillard encounter and I think it is good to document it (troubleshooting section) or if possible have a part of our checks (not sure). 

Issue:
```
$ crc setup
[...]
INFO Setting up libvirt 'crc' network
INFO Starting libvirt 'crc' network
FATA exit status 1 : error: Failed to start network crc
error: COMMAND_FAILED: '/usr/sbin/iptables -w10 -w --table filter --insert LIBVIRT_INP --in-interface crc --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: No chain/target/match by that name.
```
Solution:
```
$ crc delete
$ sudo iptables -F
$ sudo restart firewalld 
$ sudo systemctl restart libvirtd 
$ crc setup 
```

**Comment by robin-owen** [comment] 2019-08-30 15:59
What's the cause of the issue?

**Comment by robin-owen** [comment] 2020-02-04 12:50
We've had a troubleshooting section for quite a while now.

@praveenkumar Does the reported issue still occur? If we still need to document this, I'll leave this issue open. Otherwise, I think we can safely close it.

**Comment by gbraad** [comment] 2020-02-04 12:54
I belioeve this is something that could be detected and fixed by the setup command.

**Closed by gbraad** 2020-02-04 12:54 UTC
Labels: kind/documentation
