### ISSUE TITLE
[Feature] add support for qemu to support apple silicon

### ISSUE THREAD

**Issue by gayanper** [code-ready/crc#2881] opened 2021-12-12 11:14 UTC
Today one of the main reason that CRC cannot be used in apple silicon is it depends on hyperkit for macos virtualization. But project like lima,colima and RancherDesktop use qemu for virtualization. Since qemu is capable of using the MacOS native hypervisor its capable to run VMs in a similar manner like hyperkit without emulation.

switching the qemu will enable CRC to take the first step on running on both Intel and arm64 Macs.

**Comment by gbraad** [comment] 2021-12-13 03:18
We are investigating this already, but as part of the Virtualization Framework. There were compelling reasons before, like performance to go with qemu, but the issue is to maintain a specific binary release for this executable that can be cumbersome. At the moment looking into comparing the two options. Feedback is much appreciated.

@cfergeau @praveenkumar Thoughts?

**Comment by cfergeau** [comment] 2021-12-13 09:27
I'm currently exploring making use of Virtualization Framework through https://github.com/Code-Hex/vz
Progress so far is in https://github.com/cfergeau/machine-driver-vz. This is a standalone binary, not yet a proper machine driver, but  this can already start a crc VM. Next goal is to be able to use vsock/usermode networking with it and turn it into a machine driver.

From a Red Hat/supply chain perspective, we'd indeed have to make/maintain our own macOS QEMU builds if we were going to make use of it. QEMU is a 2 million lines code base with the CVEs that go with such a big code base, so I'm strongly biased towards Virtualization Framework which we don't need to build/maintain on our own since it's already part of macOS.  https://github.com/Code-Hex/vz is just some objc->go bindings for Virtualization Framework and is less than 1000 lines. This means using macOS 11 or newer though.

**Comment by gbraad** [comment] 2022-01-06 05:10
Closing in favor of tracking the investigation issue #1850

**Closed** 2022-01-06 05:10 UTC
Labels: tags/help wanted, kind/question, priority/major, os/macos, status/need more information
