### ISSUE TITLE
Unable to perform cert check when using native SSH implementation after key pivot

### ISSUE THREAD

**Issue by jsliacan** [code-ready/crc#1549] opened 2020-09-28 10:48 UTC
Error checking `/var/lib/kubelet/pki/kubelet-client-current.pem` during the `crc start` process on Win10 with `4.6.0-fc.7` bundle. 

### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: 1.16.0+9cfefb2
OpenShift version: 4.6.0-fc.7 (not embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.6.0-fc.7)
Disk Usage:      12.99GB of 32.72GB (Inside the CRC VM)
Cache Usage:     15.34GB
Cache Directory: C:\Users\crcqe\.crc\cache
```

## CRC config
```bash
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start`

### Expected
CRC starts without errors.

### Actual
```
> crc setup 
INFO Checking if oc binary is cached
INFO Checking if podman remote binary is cached
INFO Checking if goodhosts binary is cached
INFO Checking if CRC bundle is cached in '$HOME/.crc'
INFO Checking minimum RAM requirements
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
Setup is complete, you can now run 'crc start -b $bundlename' to start the OpenShift cluster
```
and 
```
> crc start -b C:\Users\crcqe\Downloads\crc_hyperv_4.6.0-fc.7.crcbundle -p C:\Users\crcqe\Downloads\pull-secret --log-level=debug
DEBU CodeReady Containers version: 1.16.0+9cfefb2
DEBU OpenShift version: 4.6.0-fc.7 (not embedded in binary)
DEBU Total memory of system is 34186895360 bytes
DEBU Unable to find out if a new version is available: Get https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
INFO Checking if oc binary is cached
DEBU Running 'C:\Users\crcqe\.crc\bin\oc\oc.exe version --client'
DEBU Found oc.exe version 4.5.9
DEBU oc binary already cached
INFO Checking if podman remote binary is cached
DEBU Currently podman remote is not supported
INFO Checking if goodhosts binary is cached
DEBU goodhost binary already cached
INFO Checking minimum RAM requirements
DEBU Total memory of system is 34186895360 bytes
INFO Checking if running as normal user
INFO Checking Windows 10 release
INFO Checking Windows edition
DEBU Running on Windows Professional edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
INFO Loading bundle: crc_hyperv_4.6.0-fc.7.crcbundle ...
INFO Checking size of the disk image C:\Users\crcqe\.crc\cache\crc_hyperv_4.6.0-fc.7\crc.vhdx ...
INFO Creating CodeReady Containers VM for OpenShift 4.6.0-fc.7...
DEBU Waiting until ssh is available
DEBU About to run SSH command:
exit 0
DEBU SSH command results: err: <nil>, output:
INFO CodeReady Containers VM is running
INFO Generating new SSH Key pair ...
DEBU About to run SSH command:
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlJjiTVo9qxTd+pOX+pyrmuKnrPswj7LDFGC1jYjphV/WdCj7cp3EqADnlEgFkEAObNvj7SnEXOEdZpDJQK+7qe5dQ3lzZX7tBsuk0+lXVtCubd6uDObHHcBXF6QkWXHSFq8fPsrLsRLcmjzXQ5HbgJ+ONFt6HOZwG226QBTx6Hxo8gi0tQCpPtHOr1bD8/xYDXjgxSXtNU6hlcjQXlzsJ5ThqQge7l8LsNDAARBfbxFBcQbUh1KtzPQe/N6lSFax/r7Vqw66Vb5u/HS5gVWskzKonw97zRO3ilj1s6eL9DnPL+8SVBZEdMcw5SsjCb0+iy9a2VIx8dbAIiio/8R8x
' > /home/core/.ssh/authorized_keys; chmod 644 /home/core/.ssh/authorized_keys
DEBU SSH command results: err: <nil>, output:
INFO Copying kubeconfig file to instance dir ...
DEBU Copying 'C:\Users\crcqe\.crc\cache\crc_hyperv_4.6.0-fc.7\kubeconfig' to 'C:\Users\crcqe\.crc\machines\crc\kubeconfig'
INFO Starting network time synchronization in CodeReady Containers VM
DEBU About to run SSH command:
sudo timedatectl set-ntp on
DEBU SSH command results: err: <nil>, output:
INFO Verifying validity of the cluster certificates ...
DEBU About to run SSH command:
date --date="$(sudo openssl x509 -in /var/lib/kubelet/pki/kubelet-client-current.pem -noout -enddate | cut -d= -f 2)" --iso-8601=seconds
DEBU SSH command results: err: <nil>, output:
ERRO Failed to check certificate validity: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
Failed to check certificate validity: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

**Comment by gbraad** [comment] 2020-09-29 00:25
This is caused by the pivot of the ssh key; the configuration did not consider using the new key.

**Comment by guillaumerose** [comment] 2020-09-30 20:15
Can you try with latest master ? It should be fixed now.

**Closed** 2020-10-06 09:27 UTC
Labels: kind/bug
