### ISSUE TITLE
[BUG] Wait till auth operator ready to serve the cluster

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#905] opened 2019-12-19 14:48 UTC
Right now we just wait for 3 mins and hope everything just works but this is not always true so if you check the `crc status` just after start you will see that auth operator are still in the process and not available.

**Comment by cfergeau** [comment] 2019-12-19 14:55
Duplicate of #394

**Closed by cfergeau** 2019-12-19 14:55 UTC
Labels: kind/bug
