### ISSUE TITLE
crc 1.31.2 installation is failing on RHEL7;

### ISSUE THREAD

**Issue by rupeshad81** [code-ready/crc#2677] opened 2021-08-27 10:05 UTC
After running the command : `crc config set skip-check-daemon-systemd-unit true` and `crc config set skip-check-daemon-systemd-sockets true`

It had proceeded further , but it is not able to do `crc start`.
```
[crc@eaas-crc ~]$ crc start --cpus 12 --memory 40000 --log-level debug
DEBU HTTP-PROXY: http://10.232.233.70:8080, HTTPS-PROXY: http://10.232.233.70:8080, NO-PROXY: 127.0.0.1,localhost,127.0.0.1,localhost,.corp.amdocs.com,.apps-crc.testing,.crc.testing,api-int.crc.testing, proxyCAFile:
DEBU CodeReady Containers version: 1.31.2+19538dab
DEBU OpenShift version: 4.8.4 (embedded in executable)
DEBU Running 'crc start'
DEBU Total memory of system is 42020716544 bytes
DEBU No new version available. The latest version is 1.31.2
DEBU Found binary path at /home/crc/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:33893
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Fetching VM..."
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Closing plugin on server side"
DEBU Checking if systemd-resolved.service is running
DEBU Running 'systemctl status systemd-resolved.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit systemd-resolved.service could not be found.
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
DEBU Running '/home/crc/.crc/bin/crc-admin-helper-linux --version'
DEBU Found crc-admin-helper-linux version 0.0.6
DEBU crc-admin-helper executable already cached
INFO Checking for obsolete admin-helper executable
DEBU Checking if an older admin-helper executable is installed
DEBU No older admin-helper executable found
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
DEBU Total memory of system is 42020716544 bytes
INFO Checking if crc executable symlink exists
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU /dev/kvm was found
INFO Checking if libvirt is installed
DEBU Checking if 'virsh' is available
DEBU 'virsh' was found in /usr/bin/virsh
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability
DEBU Running 'virsh --readonly --connect qemu:///system capabilities'
DEBU Found x86_64 hypervisor with 'hvm' capabilities
INFO Checking if user is part of libvirt group
DEBU Checking if current user is part of the libvirt group
DEBU Current user is already in the libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
DEBU Checking if libvirtd service is running
DEBU Running 'systemctl status virtqemud.socket'
DEBU Command failed: exit status 3
DEBU stdout: * virtqemud.socket
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
DEBU stderr:
DEBU virtqemud.socket is neither running nor listening
DEBU Running 'systemctl status libvirtd.socket'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit libvirtd.socket could not be found.
DEBU libvirtd.socket is neither running nor listening
DEBU Running 'systemctl status virtqemud.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit virtqemud.service could not be found.
DEBU virtqemud.service is neither running nor listening
DEBU Running 'systemctl status libvirtd.service'
DEBU libvirtd.service is running
INFO Checking if a supported libvirt version is installed
DEBU Checking if libvirt version is >=3.4.0
DEBU Running 'virsh -v'
INFO Checking if crc-driver-libvirt is installed
DEBU Checking if crc-driver-libvirt is installed
DEBU Running '/home/crc/.crc/bin/crc-driver-libvirt version'
DEBU Found crc-driver-libvirt version 0.13.1
DEBU crc-driver-libvirt is already installed
INFO Checking crc daemon systemd socket units
WARN Skipping above check...
INFO Checking if systemd-networkd is running
DEBU Checking if systemd-networkd.service is running
DEBU Running 'systemctl status systemd-networkd.service'
DEBU Command failed: exit status 4
DEBU stdout:
DEBU stderr: Unit systemd-networkd.service could not be found.
DEBU systemd-networkd.service is not running
INFO Checking if NetworkManager is installed
DEBU Checking if 'nmcli' is available
DEBU 'nmcli' was found in /usr/bin/nmcli
INFO Checking if NetworkManager service is running
DEBU Checking if NetworkManager.service is running
DEBU Running 'systemctl status NetworkManager.service'
DEBU NetworkManager.service is already running
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
DEBU Checking NetworkManager configuration
DEBU NetworkManager configuration is good
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
DEBU Checking dnsmasq configuration
DEBU dnsmasq configuration is good
INFO Checking if libvirt 'crc' network is available
DEBU Checking if libvirt 'crc' network exists
DEBU Running 'virsh --connect qemu:///system net-info crc'
DEBU Checking if libvirt 'crc' definition is up to date
DEBU Running 'virsh --connect qemu:///system net-dumpxml --inactive crc'
DEBU libvirt 'crc' network has the expected value
INFO Checking if libvirt 'crc' network is active
DEBU Checking if libvirt 'crc' network is active
DEBU Running 'virsh --connect qemu:///system net-info crc'
DEBU libvirt 'crc' network is already active
DEBU Checking file: /home/crc/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/crc/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:39813
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Fetching VM..."
INFO Starting CodeReady Containers VM for OpenShift 4.8.4...
DEBU Updating CRC VM configuration
DEBU (crc) Calling .GetConfigRaw
DEBU (crc) Calling .Start
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Starting VM crc"
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Validating network"
DEBU (crc) DBG | time="2021-08-27T08:24:38+01:00" level=debug msg="Validating storage pool"
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="IP address: 192.168.130.11"
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=info msg="Found IP for machine: 192.168.130.11"
DEBU (crc) Calling .GetConfigRaw
DEBU Waiting for machine to be running, this may take a few minutes...
DEBU retry loop: attempt 0
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="Getting current state..."
DEBU Machine is up and running!
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="Getting current state..."
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-08-27T08:24:44+01:00" level=debug msg="IP address: 192.168.130.11"
INFO CodeReady Containers instance is running with IP 192.168.130.11
DEBU Waiting until ssh is available
DEBU retry loop: attempt 0
DEBU Running SSH command: exit 0
DEBU Using ssh private keys: [/home/crc/.crc/cache/crc_libvirt_4.8.4/id_ecdsa_crc /home/crc/.crc/machines/crc/id_ecdsa]
DEBU SSH command results: err: dial tcp 192.168.130.11:22: i/o timeout, output:
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : dial tcp 192.168.130.11:22: i/o timeout\n - sleeping 1s
...
DEBU retry loop: attempt 91
DEBU Running SSH command: exit 0
DEBU Using ssh private keys: [/home/crc/.crc/cache/crc_libvirt_4.8.4/id_ecdsa_crc /home/crc/.crc/machines/crc/id_ecdsa]
DEBU SSH command results: err: dial tcp 192.168.130.11:22: connect: no route to host, output:
DEBU error: Temporary error: ssh command error:
command : exit 0
err     : dial tcp 192.168.130.11:22: connect: no route to host\n - sleeping 1s
DEBU RetryAfter timeout after 92 tries
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU (crc) DBG | time="2021-08-27T08:29:45+01:00" level=debug msg="Closing plugin on server side"
DEBU Making call to close connection to plugin binary
Failed to connect to the CRC VM with SSH -- host might be unreachable: Temporary error: ssh command error:
command : exit 0
err     : dial tcp 192.168.130.11:22: i/o timeout\n (x3)
Temporary error: ssh command error:
command : exit 0
err     : dial tcp 192.168.130.11:22: connect: no route to host\n (x89)
```

```
[crc@eaas-crc ~]$ crc status
CRC VM:          Running
OpenShift:       Degraded (v4.8.4)
Disk Usage:      6.279GB of 32.74GB (Inside the CRC VM)
Cache Usage:     16.15GB
Cache Directory: /home/crc/.crc/cache
```

**Comment by rupeshad81** [comment] 2021-08-29 06:37
Hi,
Please check below:
[crc@eaas-crc ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)


Thanks

**Comment by gbraad** [comment] 2021-08-29 12:44
Laptop, baremetal or a Virtual Machine?

**Comment by rupeshad81** [comment] 2021-08-29 12:47
Hi,
It is Virtual Machine.

Thanks

**Comment by gbraad** [comment] 2021-08-29 13:03
Which I guessed. It shows erratic behavior. We do not support nested virtualization setups. While it is known to work with KVM and HyperV, so unexpected behavior has been reported. Especially in combination with VMware. We are unable to verify and test this. All you can do is gather logs and provide detailed information, but we are unable to resolve this. Try to run this without a nested setup and verify your installation works.

**Comment by rupeshad81** [comment] 2021-08-29 13:08
Hi,

We were able to install till 4.7.11 on the same VM , without any issues.
How it is changed from 4.8.x , any changes in setup, we should have some workaround.
Or else Redhat should provide the proper setup , which is compatible for VM. same way like 4.7.11.

So let us know the findings.

Thanks

**Comment by gbraad** [comment] 2021-08-29 13:15
The single node setup is not a supported setup and is O ky offered for development purposes in a best effort approach. We have already experienced a lot of issues just delivering 4.8 as is for this purpose as according to #2509. If you need to run a supported setup, please use the OpenShift installer.

**Comment by rupeshad81** [comment] 2021-08-29 13:21
Hi,

For development purpose we need this setup, as single node. Further which customer will deploy their deployments on the cluster levels and then production clusters.

But this get failed with various different errors , so it is very difficult to troubleshoot this errors.

Thanks

**Comment by gbraad** [comment] 2021-08-29 13:22
> we should have some workaround.

Use the OpenShift installer to setup an environment using VMware as the hypervisor of your choice. You can 'follow' (read: learn from) how to run a single node setup from the code-ready/snc repo. This will not be a one to one mapping, but would avoid any possible issues caused by a nested virtualization setup.

**Comment by rupeshad81** [comment] 2021-08-29 13:25
Hi,

Please can you share the proper steps to follow and instruction to run the setup.


Thanks

**Comment by gbraad** [comment] 2021-08-29 13:32
We are not able to do so. The snc repo can provide some guidance, but since this co cerns VMware we could not verify any of the steps.

You would use the installer with a forced single master and worker setup, but allow to run this converged on a single node.

I can not guarantee this will even work, as we only test this setup on KVM, and using gcp. Only recently 4.8 started work on a single node setup for edge purposes,  it it is still early days. So, `your mileage may vary`.

**Comment by rupeshad81** [comment] 2021-08-29 16:46
Hi,

When there will be stable CRC version 4.8.x to installed it.

Thanks

**Comment by gbraad** [comment] 2021-08-30 02:17
CRC 4.8.x is stable for the intended use of installing on baremetal and/or laptop use, as these are our primary targets.

For use on nested virtualization your mileage may vary; tested to work on KVM+HyperV, and HyperV+KVM, HyperV+HyperV and KVM+KVM. Any other combination involving a hypervisor other than these can result in unexpected results.

**Comment by gbraad** [comment] 2021-08-30 02:19
Note: we might investigate this over time, but we have higher priorities issues than making this work in combination with VMware.
Closing as a duplicate of #2628

**Closed by gbraad** 2021-08-30 02:19 UTC
Labels: os/linux, nested-virt, resolution/unsupported

**Comment by cfergeau** [comment] 2021-08-30 13:40
If you can consistently reproduce the `Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x11)` error after `crc cleanup && crc setup && crc start --log-level debug` (only these 3 commands with no additional steps or arguments), I'd be interested in the output of `crc start` with debugging output.

**Comment by rupeshad81** [comment] 2021-08-31 10:09
Hi,
For now we had removed the setup and installing the crc 1.29.1 with ocp version 4.7.18.

But getting this issue for the same version.

**Comment by gbraad** [comment] 2021-08-31 10:47
> But getting this issue for the same version.

Which issue ?

**Comment by rupeshad81** [comment] 2021-08-31 10:53
Hi,

Failed to renew TLS certificates  => 1.29.1


Both for 1.31.1 and 1.31.2
no route to host\n (x89)
pull secret not updated to disk (x11)

**Comment by gbraad** [comment] 2021-08-31 11:31
the pull-secret not updating and no route to host is most likely related to not getting a connection established.

the failed TLS certificate is a timing sensitive process, so nested virtualization can interfere here. this has been reported before. so in that case, not much that can be done.
