### ISSUE TITLE
Where could I download the bundle file?

### ISSUE THREAD

**Issue by andrejpetras** [code-ready/crc#387] opened 2019-08-07 07:40 UTC
Hi, 

I would like to install the crc. 
Where could I download the bundle file? 
The bundle in the github is protected by password.
Would it be possible to get a password for the bundle?

Best Regards,
Andrej

**Comment by gbraad** [comment] 2019-08-07 10:42
Duplicate of #263
There is no public bundle available, so the one you refer is it likely from the CI. If so, this is not for being shared.

**Closed by gbraad** 2019-08-07 10:42 UTC
