### ISSUE TITLE
Failed to start HAProxy Load Balancer

### ISSUE THREAD

**Issue by rupeshad81** [code-ready/crc#2731] opened 2021-09-16 08:42 UTC
Hi,
```
[crc@eaas-crc ~]$ crc version
CodeReady Containers version: 1.32.1+4d40571f
OpenShift version: 4.8.5 (embedded in executable)
[crc@eaas-crc ~]$ oc version
Client Version: 4.8.5
Server Version: 4.8.5
Kubernetes Version: v1.21.1+9807387
```
While starting the HAProxy, it is giving the errors.
```
[root@eaas-crc ~]# systemctl status haproxy
â haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-09-16 03:10:35 EDT; 1h 31min ago
  Process: 34178 ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $OPTIONS (code=exited, status=1/FAILURE)
  Process: 34175 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 34178 (code=exited, status=1/FAILURE)

Sep 16 03:10:35 eaas-crc haproxy[34178]:         [SPOE] spoe
Sep 16 03:10:35 eaas-crc haproxy[34178]:         [COMP] compression
Sep 16 03:10:35 eaas-crc haproxy[34178]:         [TRACE] trace
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
Sep 16 03:10:35 eaas-crc haproxy[34178]: Using epoll() as the polling mechanism.
Sep 16 03:10:35 eaas-crc systemd[1]: haproxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 03:10:35 eaas-crc systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 16 03:10:35 eaas-crc systemd[1]: Failed to start HAProxy Load Balancer.
```

```
[root@eaas-crc ~]# journalctl -u  haproxy
-- Logs begin at Thu 2021-09-16 01:57:07 EDT, end at Thu 2021-09-16 03:23:24 EDT. --
Sep 16 02:40:47 eaas-crc systemd[1]: Starting HAProxy Load Balancer...
Sep 16 02:40:47 eaas-crc haproxy[33853]: [WARNING] 258/024047 (33853) : config : log format ignored for frontend 'apps' since it has no log address.
Sep 16 02:40:47 eaas-crc haproxy[33853]: [WARNING] 258/024047 (33853) : config : log format ignored for frontend 'app' since it has no log address.
Sep 16 02:40:47 eaas-crc haproxy[33853]: [WARNING] 258/024047 (33853) : config : log format ignored for frontend 'api' since it has no log address.
Sep 16 02:40:47 eaas-crc haproxy[33853]: Note: setting global.maxconn to 2000.
Sep 16 02:40:47 eaas-crc haproxy[33853]: Available polling systems :
Sep 16 02:40:47 eaas-crc haproxy[33853]:       epoll : pref=300,  test result OK
Sep 16 02:40:47 eaas-crc haproxy[33853]:        poll : pref=200,  test result OK
Sep 16 02:40:47 eaas-crc haproxy[33853]:      select : pref=150,  test result FAILED
Sep 16 02:40:47 eaas-crc haproxy[33853]: Total: 3 (2 usable), will use epoll.
Sep 16 02:40:47 eaas-crc haproxy[33853]: Available filters :
Sep 16 02:40:47 eaas-crc haproxy[33853]:         [SPOE] spoe
Sep 16 02:40:47 eaas-crc haproxy[33853]:         [COMP] compression
Sep 16 02:40:47 eaas-crc haproxy[33853]:         [TRACE] trace
Sep 16 02:40:47 eaas-crc haproxy[33853]: [ALERT] 258/024047 (33853) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 02:40:47 eaas-crc haproxy[33853]: [ALERT] 258/024047 (33853) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 02:40:47 eaas-crc haproxy[33853]: [ALERT] 258/024047 (33853) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
Sep 16 02:40:47 eaas-crc haproxy[33853]: Using epoll() as the polling mechanism.
Sep 16 02:40:47 eaas-crc systemd[1]: haproxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 02:40:47 eaas-crc systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 16 02:40:47 eaas-crc systemd[1]: Failed to start HAProxy Load Balancer.
Sep 16 03:10:35 eaas-crc systemd[1]: Starting HAProxy Load Balancer...
Sep 16 03:10:35 eaas-crc haproxy[34178]: [WARNING] 258/031035 (34178) : config : log format ignored for frontend 'apps' since it has no log address.
Sep 16 03:10:35 eaas-crc haproxy[34178]: [WARNING] 258/031035 (34178) : config : log format ignored for frontend 'app' since it has no log address.
Sep 16 03:10:35 eaas-crc haproxy[34178]: [WARNING] 258/031035 (34178) : config : log format ignored for frontend 'api' since it has no log address.
Sep 16 03:10:35 eaas-crc haproxy[34178]: Note: setting global.maxconn to 2000.
Sep 16 03:10:35 eaas-crc haproxy[34178]: Available polling systems :
Sep 16 03:10:35 eaas-crc haproxy[34178]:       epoll : pref=300,  test result OK
Sep 16 03:10:35 eaas-crc haproxy[34178]:        poll : pref=200,  test result OK
Sep 16 03:10:35 eaas-crc haproxy[34178]:      select : pref=150,  test result FAILED
Sep 16 03:10:35 eaas-crc haproxy[34178]: Total: 3 (2 usable), will use epoll.
Sep 16 03:10:35 eaas-crc haproxy[34178]: Available filters :
Sep 16 03:10:35 eaas-crc haproxy[34178]:         [SPOE] spoe
Sep 16 03:10:35 eaas-crc haproxy[34178]:         [COMP] compression
Sep 16 03:10:35 eaas-crc haproxy[34178]:         [TRACE] trace
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
Sep 16 03:10:35 eaas-crc haproxy[34178]: Using epoll() as the polling mechanism.
Sep 16 03:10:35 eaas-crc systemd[1]: haproxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 03:10:35 eaas-crc systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 16 03:10:35 eaas-crc systemd[1]: Failed to start HAProxy Load Balancer.
```

```
[root@eaas-crc ~]# cat /etc/haproxy/haproxy.cfg
global
        debug

defaults
        log global
        mode    http
        timeout connect 5000
        timeout client 5000
        timeout server 5000

frontend apps
    bind 192.168.2.101:443
    option tcplog
    mode tcp
    default_backend apps

backend apps
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:443 check

frontend app
    bind 192.168.2.101:80
    option tcplog
    mode tcp
    default_backend app

backend app
    mode tcp
    balance roundrobin
    server webserver1 192.168.130.11:80 check

frontend api
    bind 192.168.2.101:6443
    option tcplog
    mode tcp
    default_backend api

backend api
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:6443 check
```

**Comment by gbraad** [comment] 2021-09-16 09:17
Please use the issue template

**Comment by rupeshad81** [comment] 2021-09-16 09:20
Hi,

 issue template Means ?

**Comment by cfergeau** [comment] 2021-09-16 09:45
Is this the same as https://github.com/code-ready/crc/issues/2664 ?

**Comment by gbraad** [comment] 2021-09-16 09:45
> issue template Means ?

The thing you Ctrl+A remove on filing an issue

-----

### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Expected


### Actual


### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by rupeshad81** [comment] 2021-09-16 11:33
Hi,

Is this the same as #2664 ?   No , it is different issue

**Comment by rupeshad81** [comment] 2021-09-16 11:37
Hi,
Please check the below update


[crc@eaas-crc ~]$ crc version
CodeReady Containers version: 1.32.1+4d40571f
OpenShift version: 4.8.5 (embedded in executable)


[crc@eaas-crc ~]$ crc status
CRC VM:          Running
OpenShift:       Running (v4.8.5)
Disk Usage:      14.11GB of 32.74GB (Inside the CRC VM)
Cache Usage:     15.96GB
Cache Directory: /home/crc/.crc/cache
[crc@eaas-crc ~]$ crc config view
- consent-telemetry                     : no
- http-proxy                            : http://10.232.233.70:8080
- https-proxy                           : http://10.232.233.70:8080
- no-proxy                              : 127.0.0.1,localhost,.corp.amdocs.com,.apps-crc.testing,.crc.testing
- skip-check-daemon-systemd-sockets     : true
- skip-check-daemon-systemd-unit        : true
[crc@eaas-crc ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

**Comment by cfergeau** [comment] 2021-09-16 11:46
```
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 03:10:35 eaas-crc haproxy[34178]: [ALERT] 258/031035 (34178) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
```

Either something is already using the 443, 80, 6443 ports, or the 192.168.2.101 IP is incorrect. We provide a sample haproxy.conf file in our documentation which should work for basic use, but the one you are using is different. Installing/configuring/troubleshooting haproxy is not something we'll be very good at, and not directly related to crc.

**Comment by rupeshad81** [comment] 2021-09-16 11:58
Hi,

Please can you provide the documentation for  RHEL 8.4 to configure the HAProxy.

**Comment by cfergeau** [comment] 2021-09-16 12:43
I don't know if there is generic RHEL documentation about this, and I also don't know what you are trying to achieve. The crc-specific documentation is https://crc.dev/crc/#setting-up-remote-server_gsg

**Comment by rupeshad81** [comment] 2021-09-16 13:01
Hi,

I am configure below:

Expose the crc to external access
Install and configure ha proxy to bridge the internal virtual nic to external address

**Comment by cfergeau** [comment] 2021-09-16 13:04
This should be covered in the link I gave before, https://crc.dev/crc/#setting-up-remote-server_gsg

**Comment by rupeshad81** [comment] 2021-09-16 14:01
Hi,

Yes ,as per the document it has been configured, But it is not getting start.

It is getting issue.

[root@eaas-crc ~]# systemctl status haproxy
â haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-09-16 07:39:28 EDT; 2h 20min ago
  Process: 5056 ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $OPTIONS (code=exited, status=1/FAILURE)
  Process: 5053 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 5056 (code=exited, status=1/FAILURE)

Sep 16 07:39:28 eaas-crc haproxy[5056]:         [SPOE] spoe
Sep 16 07:39:28 eaas-crc haproxy[5056]:         [COMP] compression
Sep 16 07:39:28 eaas-crc haproxy[5056]:         [TRACE] trace
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
Sep 16 07:39:28 eaas-crc haproxy[5056]: Using epoll() as the polling mechanism.
Sep 16 07:39:28 eaas-crc systemd[1]: haproxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 07:39:28 eaas-crc systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 16 07:39:28 eaas-crc systemd[1]: Failed to start HAProxy Load Balancer.


[root@eaas-crc ~]# journalctl -u haproxy
-- Logs begin at Thu 2021-09-16 06:47:31 EDT, end at Thu 2021-09-16 07:43:33 EDT. --
Sep 16 07:39:28 eaas-crc systemd[1]: Starting HAProxy Load Balancer...
Sep 16 07:39:28 eaas-crc haproxy[5056]: [WARNING] 258/073928 (5056) : config : log format ignored for frontend 'apps' since it has no log address.
Sep 16 07:39:28 eaas-crc haproxy[5056]: [WARNING] 258/073928 (5056) : config : log format ignored for frontend 'app' since it has no log address.
Sep 16 07:39:28 eaas-crc haproxy[5056]: [WARNING] 258/073928 (5056) : config : log format ignored for frontend 'api' since it has no log address.
Sep 16 07:39:28 eaas-crc haproxy[5056]: Note: setting global.maxconn to 2000.
Sep 16 07:39:28 eaas-crc haproxy[5056]: Available polling systems :
Sep 16 07:39:28 eaas-crc haproxy[5056]:       epoll : pref=300,  test result OK
Sep 16 07:39:28 eaas-crc haproxy[5056]:        poll : pref=200,  test result OK
Sep 16 07:39:28 eaas-crc haproxy[5056]:      select : pref=150,  test result FAILED
Sep 16 07:39:28 eaas-crc haproxy[5056]: Total: 3 (2 usable), will use epoll.
Sep 16 07:39:28 eaas-crc haproxy[5056]: Available filters :
Sep 16 07:39:28 eaas-crc haproxy[5056]:         [SPOE] spoe
Sep 16 07:39:28 eaas-crc haproxy[5056]:         [COMP] compression
Sep 16 07:39:28 eaas-crc haproxy[5056]:         [TRACE] trace
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend apps: cannot bind socket [192.168.2.101:443]
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend app: cannot bind socket [192.168.2.101:80]
Sep 16 07:39:28 eaas-crc haproxy[5056]: [ALERT] 258/073928 (5056) : Starting frontend api: cannot bind socket [192.168.2.101:6443]
Sep 16 07:39:28 eaas-crc haproxy[5056]: Using epoll() as the polling mechanism.
Sep 16 07:39:28 eaas-crc systemd[1]: haproxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 07:39:28 eaas-crc systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 16 07:39:28 eaas-crc systemd[1]: Failed to start HAProxy Load Balancer.


[root@eaas-crc ~]# echo $CRC_IP
192.168.130.11
[root@eaas-crc ~]# cat /etc/haproxy/haproxy.cfg
global
        debug

defaults
        log global
        mode    http
        timeout connect 5000
        timeout client 5000
        timeout server 5000

frontend apps
    bind 192.168.2.101:443
    option tcplog
    mode tcp
    default_backend apps

backend apps
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:443 check

frontend app
    bind 192.168.2.101:80
    option tcplog
    mode tcp
    default_backend app

backend app
    mode tcp
    balance roundrobin
    server webserver1 192.168.130.11:80 check

frontend api
    bind 192.168.2.101:6443
    option tcplog
    mode tcp
    default_backend api

backend api
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:6443 check

**Comment by cfergeau** [comment] 2021-09-16 14:04
The sample config from crc's documentation is quite different from yours.
```
global
    log /dev/log local0

defaults
    balance roundrobin
    log global
    maxconn 100
    mode tcp
    timeout connect 5s
    timeout client 500s
    timeout server 500s

listen apps
    bind 0.0.0.0:80
    server crcvm $CRC_IP:80 check

listen apps_ssl
    bind 0.0.0.0:443
    server crcvm $CRC_IP:443 check

listen api
    bind 0.0.0.0:6443
    server crcvm $CRC_IP:6443 check
```

**Comment by rupeshad81** [comment] 2021-09-16 14:23
Hi,

If we keep this configuration:

global
    log /dev/log local0

defaults
    balance roundrobin
    log global
    maxconn 100
    mode tcp
    timeout connect 5s
    timeout client 500s
    timeout server 500s

listen apps
    bind 0.0.0.0:80
    server crcvm 192.168.130.11:80 check

listen apps_ssl
    bind 0.0.0.0:443
    server crcvm 192.168.130.11:443 check

listen api
    bind 0.0.0.0:6443
    server crcvm 192.168.130.11:6443 check

Then getting below Issue:


[root@eaas-crc ~]# systemctl restart haproxy

Broadcast message from systemd-journald@eaas-crc (Thu 2021-09-16 10:18:59 EDT):

haproxy[7307]: proxy apps has no server available!

[root@eaas-crc ~]#
Message from syslogd@eaas-crc at Sep 16 10:18:59 ...
 haproxy[7307]:proxy apps has no server available!

Broadcast message from systemd-journald@eaas-crc (Thu 2021-09-16 10:19:00 EDT):

haproxy[7307]: proxy apps_ssl has no server available!


Message from syslogd@eaas-crc at Sep 16 10:19:00 ...
 haproxy[7307]:proxy apps_ssl has no server available!

**Comment by rupeshad81** [comment] 2021-09-16 14:25
Hi,

But we keep this configuration , it get worked.

global
        debug

defaults
        log global
        mode    http
        timeout connect 5000
        timeout client 5000
        timeout server 5000

frontend apps
    bind 0.0.0.0:443
    option tcplog
    mode tcp
    default_backend apps

backend apps
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:443 check

frontend app
    bind 0.0.0.0:80
    option tcplog
    mode tcp
    default_backend app

backend app
    mode tcp
    balance roundrobin
    server webserver1 192.168.130.11:80 check

frontend api
    bind 0.0.0.0:6443
    option tcplog
    mode tcp
    default_backend api

backend api
    mode tcp
    balance roundrobin
    option ssl-hello-chk
    server webserver1 192.168.130.11:6443 check


[root@eaas-crc ~]# systemctl restart haproxy
[root@eaas-crc ~]# systemctl status haproxy
â haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-09-16 10:22:55 EDT; 10s ago
  Process: 7361 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 7364 (haproxy)
    Tasks: 2 (limit: 287884)
   Memory: 2.2M
   CGroup: /system.slice/haproxy.service
           ââ7364 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           ââ7366 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

Sep 16 10:22:55 eaas-crc haproxy[7364]:       epoll : pref=300,  test result OK
Sep 16 10:22:55 eaas-crc haproxy[7364]:        poll : pref=200,  test result OK
Sep 16 10:22:55 eaas-crc haproxy[7364]:      select : pref=150,  test result FAILED
Sep 16 10:22:55 eaas-crc haproxy[7364]: Total: 3 (2 usable), will use epoll.
Sep 16 10:22:55 eaas-crc haproxy[7364]: Available filters :
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [SPOE] spoe
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [COMP] compression
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [TRACE] trace
Sep 16 10:22:55 eaas-crc haproxy[7364]: Using epoll() as the polling mechanism.
Sep 16 10:22:55 eaas-crc systemd[1]: Started HAProxy Load Balancer.

**Comment by cfergeau** [comment] 2021-09-16 14:31
```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

$ rpm -q haproxy
haproxy-1.8.27-2.el8.x86_64

$ cat /etc/haproxy/haproxy.cfg
global
    log /dev/log local0

defaults
    balance roundrobin
    log global
    maxconn 100
    mode tcp
    timeout connect 5s
    timeout client 500s
    timeout server 500s

listen apps
    bind 0.0.0.0:80
    server crcvm 127.0.0.1:80 check

listen apps_ssl
    bind 0.0.0.0:443
    server crcvm 127.0.0.1:443 check

listen api
    bind 0.0.0.0:6443
    server crcvm 127.0.0.1:6443 check

$ sudo systemctl start haproxy
$

$ systemctl status haproxy 
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-09-16 16:30:11 CEST; 29s ago
  Process: 112748 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 112751 (haproxy)
    Tasks: 2 (limit: 203900)
   Memory: 2.2M
   CGroup: /system.slice/haproxy.service
           ├─112751 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           └─112753 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

Sep 16 16:30:11 ramen.dolet.fergeau.eu systemd[1]: Starting HAProxy Load Balancer...
Sep 16 16:30:11 ramen.dolet.fergeau.eu haproxy[112751]: Proxy apps started.
Sep 16 16:30:11 ramen.dolet.fergeau.eu haproxy[112751]: Proxy apps_ssl started.
Sep 16 16:30:11 ramen.dolet.fergeau.eu haproxy[112751]: Proxy api started.
Sep 16 16:30:11 ramen.dolet.fergeau.eu systemd[1]: Started HAProxy Load Balancer.
```

I don't know, the configuration from crc documentation works.

**Comment by cfergeau** [comment] 2021-09-16 14:34
> But we keep this configuration , it get worked.

Closing this issue then if you have a working configuration.

**Closed by cfergeau** 2021-09-16 14:34 UTC
Labels: resolution/invalid, status/need more information

**Comment by gbraad** [comment] 2021-09-16 15:15
Configurations need to made to match your environment. We would not know the details. 
As per comment https://github.com/code-ready/crc/issues/2731#issuecomment-920950662 this works.

**Comment by rupeshad81** [comment] 2021-09-16 15:43
Hi,

Can you explain the below "Failed"  status

What does it mean?

Sep 16 10:22:55 eaas-crc haproxy[7364]:      select : pref=150,  test result FAILED

[root@eaas-crc ~]# systemctl status haproxy
â haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-09-16 10:22:55 EDT; 10s ago
  Process: 7361 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 7364 (haproxy)
    Tasks: 2 (limit: 287884)
   Memory: 2.2M
   CGroup: /system.slice/haproxy.service
           ââ7364 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           ââ7366 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

Sep 16 10:22:55 eaas-crc haproxy[7364]:       epoll : pref=300,  test result OK
Sep 16 10:22:55 eaas-crc haproxy[7364]:        poll : pref=200,  test result OK
Sep 16 10:22:55 eaas-crc haproxy[7364]:      select : pref=150,  test result FAILED
Sep 16 10:22:55 eaas-crc haproxy[7364]: Total: 3 (2 usable), will use epoll.
Sep 16 10:22:55 eaas-crc haproxy[7364]: Available filters :
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [SPOE] spoe
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [COMP] compression
Sep 16 10:22:55 eaas-crc haproxy[7364]:         [TRACE] trace
Sep 16 10:22:55 eaas-crc haproxy[7364]: Using epoll() as the polling mechanism.
Sep 16 10:22:55 eaas-crc systemd[1]: Started HAProxy Load Balancer.

**Comment by cfergeau** [comment] 2021-09-16 15:46
This seems to be an internal haproxy implementation detail, but the next line hints it is harmless `Total: 3 (2 usable), will use epoll.`. The `select` test failed but it used a different method.

**Comment by gbraad** [comment] 2021-09-16 16:12
Important is `   Active: active (running) `. The bottom part is `stdout` logging output.
This is unrelated to CRC. Please review the haprpoxy and/or systemd documentation for this.
