### ISSUE TITLE
Explain what is an Openshift system bundle

### ISSUE THREAD

**Issue by mtarsel** [code-ready/crc#447] opened 2019-08-21 18:33 UTC
Issue #352 changed the docs to use a `.crcbundle` intead of tar.xz but I'm not clear on what this is. I did find a crc bundle in the crc-ci-jobs repo however there is a password on it. 

Could someone explain what a valid OpenShift system bundle with the .crcbundle extension is? 

[Referenced here in the docs.](https://github.com/code-ready/crc/blame/master/docs/source/getting-started/content/proc_starting-the-virtual-machine.adoc#L10)

**Comment by rgov** [comment] 2019-08-23 01:13
There is some explanation in #303 why it's hard to get ahold of this.

**Comment by rgov** [comment] 2019-08-23 01:39
Also might be worth noting that the [distributed OpenShift installers](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/) do not seem to have libvirt support enabled so you cannot shortcut the process, it seems.

**Comment by gbraad** [comment] 2019-08-26 04:12
Duplicate of #263. 
We have not released yet... this will happen soon.

**Comment by gbraad** [comment] 2019-08-26 04:13
> so you cannot shortcut the process, it seems.

This is not the same as we are doing with CRC. We do this in the background, but will never run the installer on the desktop as it is very time consuming.

**Closed by gbraad** 2019-08-26 04:12 UTC
