### ISSUE TITLE
[BUG] DNS lookup fail on mac

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#893] opened 2019-12-16 13:49 UTC
After merging https://github.com/code-ready/crc/commit/e3ad19871fd5146435ae33dd6fbbad4f41339e09 , now on the mac due to cross build it fails to resolve `foo.apps-crc.testing` from host since mac resolver doesn't work even with `dig` when using the cross build binary.

**Comment by rusenask** [comment] 2019-12-16 18:08
doesn't work on ubuntu either :|

**Comment by praveenkumar** [comment] 2019-12-17 05:16
@rusenask for ubuntu check https://github.com/code-ready/crc/issues/549 one.

**Comment by cfergeau** [comment] 2019-12-20 14:46
The problematic check has been reverted from master.
Duplicate of #854

**Comment by cfergeau** [comment] 2020-01-07 09:20
I don't think we should keep this open as long as it's referenced in #854.

**Closed by cfergeau** 2020-01-07 09:20 UTC
Labels: kind/bug
