### ISSUE TITLE
[BUG] Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

### ISSUE THREAD

**Issue by rscher** [code-ready/crc#2704] opened 2021-09-07 11:45 UTC
### General information

  * OS: RHEL 7.9 (Maipo)
  * Hypervisor: libvirt
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on:  VM

## CRC version
```bash
# Put `crc version` output here
CodeReady Containers version: 1.31.2+19538dab
OpenShift version: 4.8.4 (embedded in executable)
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
$ crc status --log-level debug
DEBU CodeReady Containers version: 1.31.2+19538dab 
DEBU OpenShift version: 4.8.4 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/crcuser/.crc/machines/crc/.crc-exist 
DEBU Checking file: /home/crcuser/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /home/crcuser/.crc/bin/crc-driver-libvirt 
DEBU Launching plugin server for driver libvirt   
DEBU Plugin server listening at address 127.0.0.1:42563 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-09-07T04:11:25-07:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-09-07T04:11:25-07:00" level=debug msg="Fetching VM..." 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU (crc) DBG | time="2021-09-07T04:11:25-07:00" level=debug msg="GetIP called for crc" 
DEBU (crc) DBG | time="2021-09-07T04:11:25-07:00" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-09-07T04:11:25-07:00" level=debug msg="IP address: 192.168.130.11" 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/crcuser/.crc/machines/crc/id_ecdsa /home/crcuser/.crc/cache/crc_libvirt_4.8.4/id_ecdsa_crc] 
DEBU SSH command results: err: <nil>, output: 32737570816 16345911296 /sysroot 
DEBU cannot get OpenShift status: stat /home/crcuser/.crc/machines/crc/kubeconfig: no such file or directory 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
CRC VM:          Running
OpenShift:       Running (v4.8.4)
Disk Usage:      16.35GB of 32.74GB (Inside the CRC VM)
Cache Usage:     16.15GB
Cache Directory: /home/crcuser/.crc/cache

## CRC config
```bash
# Put `crc config view` output here
$ crc config view
- consent-telemetry              : no
- cpus                                  : 16
- memory                              : 24672
- pull-secret-file                    : /home/crcuser/pull-secret.txt
- skip-check-daemon-systemd-sockets     : true
- skip-check-daemon-systemd-unit        : true

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VAR IANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Advanced Cluster Management"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start`

```
   Started the OpenShift cluster.

 The server is accessible via web console at:
  https://console-openshift-console.apps-crc.testing

Log in as administrator:
  Username: kubeadmin
  Password: 8WAmp-9pyz2-TAzxM-JICRF

Log in as user:
  Username: developer
  Password: developer

Use the 'oc' command line interface:
  $ eval $(crc oc-env)
  $ oc login -u developer https://api.crc.testing:6443
```

  4.  $ `oc login https://api.crc.testing:6443 -u kubeadmin -p 8WAmp-9pyz2-TAzxM-JICRF --insecure-skip-tls-verify=true`
  
```
  Error: error authenticating creds for "default-route-openshift-image-registry.apps-crc.testing": error pinging docker registry default-route-openshift-image-registry.apps-crc.testing: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority

Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")
```

 4. $ `oc config get-clusters`
```
NAME
api-crc-testing:6443
api.crc.testing:6443
```

### Expected
Login successful.

You have access to 62 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "odm8105".

### Actual
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

### Logs

=============

looks like i'm getting this issue in the latest crc build:
https://github.com/code-ready/crc/issues/2332
[BUG] Error during accessing the cluster when user switch/create a project and delete->start crc #2332

can you advise how to fix this plz ?

-Russ

**Comment by praveenkumar** [comment] 2021-09-07 12:08
@rscher if https://github.com/code-ready/crc/issues/2332 is the case then can you please clean your kubeconfig file or just try following and let us know if that work?
```
$ crc delete
$ export KUBECONFIG=/tmp/kubeconfig
$ crc start
$ oc login ...
```

**Comment by cfergeau** [comment] 2021-09-07 12:26
Can you also provide more details regarding your setup (output of dmidecode/lscpu)? This is reminiscent of older issues we saw on nested virtualization setups.

**Comment by gbraad** [comment] 2021-09-07 12:45
> Running CRC on: VM

We do not provide support on nested virtualization setups. We have only been able to verify this on KVM+KVM, KVM+HyperV, HyperV+HyperV and HyperV+KVM.

When it concerns public/private cloud providers, we had issues before, like #1830 that showed this. Make sure you aren't running old versions of the hypervisor, or a mix of distros, like Ubuntu host + RHEL.

**Comment by rscher** [comment] 2021-09-07 23:35
Thanks guys, yea we've been down this "nested virtualization" road several times and we're aware of the "limitations".
The fact is, we're been successfully using crc in this environment since  v1.25 or whatever version it was improved 
where it checks the Operators until the cluster is stable. At that point have not had any issues running the cluster
with good performance as well.
All of my envs (except this new test env to eval latest crc 1.31.2) are currently running great
with reasonable stability on workloads ... 
ive had cluster and pods running  continuously for 3 months without failures/crashes-

example from my crc 1.26 env: 

[crcuser@crc1 .crc]$ getPods 
Login Succeeded!
Using project "odm8105" on server "https://api.crc.testing:6443".
NAME                                                 READY   STATUS    RESTARTS   AGE
odm8105-odm-decisioncenter-7dfbf6d98b-pc885          1/1     Running   0            5d2h
odm8105-odm-decisionrunner-7db8bf894f-7hzh7          1/1     Running   0            120d
odm8105-odm-decisionserverconsole-66f4b867bf-ptm7d   1/1     Running   0        120d
odm8105-odm-decisionserverruntime-6dcf8b86f8-z8qx8   1/1     Running   0          120d
^C[crcuser@crc1 .crc]$ crc version
CodeReady Containers version: 1.26.0+31f06c09
OpenShift version: 4.7.8 (embedded in executable)

These fyre/castle VM envs have been successfully deployed and running with crc ever since 
the startup has these checks ...

time="2021-08-13T04:48:34-07:00" level=info msg="Operators are stable (2/3) ..."
time="2021-08-13T05:00:47-07:00" level=error msg="Cluster is not ready: cluster operators are still not stable after 12m50.551881949s"
time="2021-08-25T21:06:06-07:00" level=error msg="Cluster is not ready: cluster operators are still not stable after 12m53.542245329s"
time="2021-08-26T16:46:06-07:00" level=error msg="Cluster is not ready: cluster operators are still not stable after 12m54.071102499s"
time="2021-09-02T15:40:31-07:00" level=info msg="Operators are stable (2/3) ..."
time="2021-09-02T15:41:04-07:00" level=info msg="Operators are stable (3/3) ..."
----------------------

When I upgraded to 1.31.2 (latest), is when I just got this  #2332 issue .
I'd like to move past this  "nested virtualization story"  for purposes of evaluating the latest crc build
and see if it can be resolved.

thanks @praveenkumar  for your suggestion. i have deleted and restarted before I opened this issue.
What exactly was the resolution for #2332, specifically the code you posted in that issue ?
https://github.com/openshift/oc/blob/f94afb52dc8a3185b3b9eacaf92ec34d80f8708d/pkg/helpers/kubeconfig/smart_merge.go#L21

-Russ

**Comment by praveenkumar** [comment] 2021-09-08 03:40
>  i have deleted and restarted before I opened this issue. What exactly was the resolution for #2332, specifically the code you posted in that issue ?

@rscher That issue was  to have wrong kubeconfig file entry and we improved the code around it.


> These fyre/castle VM envs have been successfully deployed and running with crc ever since the startup has these checks ...

@rscher Those checks were making sure that once the crc start all the operators are running as expected. Every release of crc also brings in different version of OpenShift and update on the RHCOS.

**Comment by praveenkumar** [comment] 2021-09-08 03:42
Can you also put the logs from a clean `crc start --log-level debug` ?

**Comment by guillaumerose** [comment] 2021-09-08 07:48
Can you delete ~/.kube/config and try again? I suspect a wrong certificate is still in this config file.

**Comment by gbraad** [comment] 2021-09-08 09:03
> I'd like to move past this "nested virtualization story" for purposes of evaluating the latest crc build
and see if it can be resolved.

BE aware that we recently moved to 4.8, which uses more resources. And we have seen similar reports recently, so unfortunately this remains a possibility. When unexpected behavior occurs in a nested setup we are most likely not able to reproduce it ourselves. We can try assist in getting more details, ...

**Comment by rscher** [comment] 2021-09-09 07:52
Hey guys, thanks for all the feedback and suggestions. alls working on 1.31.2 .
@guillaumerose  pretty sure it was the old cert in the kubeconfig, here's what I did :

1. ran my delete_crc  script:
 ```
    crc delete -f
    crc cleanup
    virsh -c qemu:///system destroy crc
    virsh -c qemu:///system undefine crc
```

2.  ran my build_cluster script:  
 ```
    crc setup  --log-level debug 
    crc start   --log-level debug 
    # wait for cluster started message ..
    # extract cert  from openshift-ingress-operator , cp to /etc/containers/certs.d/default-route-openshift-image-registry.apps-crc.testing
     updatePodmanCerts.sh 
    # run script to add insecure registry (github.com/code-ready/crc/wiki/Adding-an-insecure-registry)
     patchCluster.sh    
```

3.  now can login without --insecure-skip-tls-verify=true
```
 [crcuser@ocp484 ~]$   kubeuser_pw=$(crc console --credentials | grep $kubeuser | gawk  '{ print $12 }')
 [crcuser@ocp484 ~]$  $(echo  "oc login -u $kubeuser  -p" $kubeuser_pw   https://api.crc.testing:6443) 
 Login successful.

 You have access to 63 projects, the list has been suppressed. You can list all projects with 'oc projects'

 Using project "odm8105".

[crcuser@ocp484 ~]$ sudo podman login  --authfile $REGISTRY_AUTH_FILE  --cert-dir $certDir -u $kubeuser   -p  $registry_pw $registry
login Succeeded!

```
Performance is actually pretty decent running average workloads ... avg %CPU of qemu:///system ~ 50-70% 
just thrilled its not 100%
```
[crcuser@ocp484~]$ virt-top -c qemu:///system --stream 
virt-top time  23:43:49 Host ocp484.castle.fyre.ibm.com x86_64 16/16CPU 2200MHz 62752MB 
   ID S RDRQ WRRQ RXBY TXBY %CPU %MEM   TIME    NAME
    1 R    0   85  33K  16K 49.9 39.0 356:08:37 crc
virt-top time  23:43:52 Host ocp484.castle.fyre.ibm.com x86_64 16/16CPU 2200MHz 62752MB 
   ID S RDRQ WRRQ RXBY TXBY %CPU %MEM   TIME    NAME
    1 R    0  121  442  656 65.3 39.0 356:09:08 crc
virt-top time  23:43:55 Host ocp484.castle.fyre.ibm.com x86_64 16/16CPU 2200MHz 62752MB 
   ID S RDRQ WRRQ RXBY TXBY %CPU %MEM   TIME    NAME
    1 R    0  139  184  132 52.2 39.0 356:09:33 crc
virt-top time  23:43:58 Host ocp484.castle.fyre.ibm.com x86_64 16/16CPU 2200MHz 62752MB 
   ID S RDRQ WRRQ RXBY TXBY %CPU %MEM   TIME    NAME
    1 R    0  106  392  659 44.1 39.0 356:09:54 crc
```

Probably sluggish due to these AMD EPYC cpu's ...  
the same crc cluster running on 16 Xeon cores (but VMWare hypervisor) screams, avg %CPU = ~30% 
```
[crcuser@ocp484~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD EPYC Processor (with IBPB)
Stepping:              2
CPU MHz:               2200.000
BogoMIPS:              4400.00
Virtualization:        AMD-V
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm art rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw retpoline_amd ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat
```

Which brings me to this question ... why does it always report  "Degraded" status ?

[crcuser@ocp484 ~]$ crc status 
CRC VM:          Running
**OpenShift:       Degraded (v4.8.4)**
Disk Usage:      20.45GB of 32.74GB (Inside the CRC VM)
Cache Usage:     16.15GB
Cache Directory: /home/crcuser/.crc/cache

-This is on RHEL 7.9, could I expect any better performance on RHEL 8.4 ? 
-Would  enable-cluster-monitoring=true  be unreasonable for this setup ?  i.e.  send %CPU of qemu vm  back to 100%

-When setting host-network-access=true,  does this allow the OpenShift Web Console or my application routes to be accessible
  outside of the RHEL host ? 
 -Is there any way to do that  with this new 4.8 based crc version ?
 

again, many thanks !
-Russ

**Comment by praveenkumar** [comment] 2021-09-10 05:22
@rscher Good to know it works now, so it was kubeconfig which causing the issue.

> Which brings me to this question ... why does it always report "Degraded" status ?

It is possible that one or more operator are in degraded state, you can try `crc status --log-level debug` and also get more info about that degraded operator using `oc get co <operator_name> -oyaml`

>This is on RHEL 7.9, could I expect any better performance on RHEL 8.4 ?

I don't have answer to this question, If there is some improvement on nested virtualization which 8.4 have then sure you can try with 8.4

>Would enable-cluster-monitoring=true be unreasonable for this setup ? i.e. send %CPU of qemu vm back to 100%

It depends if enabling cluster monitoring is hard requirement for your work then you don't have much option but monitoring is resource hungry operator which explain why %cpu went to 100%

> When setting host-network-access=true, does this allow the OpenShift Web Console or my application routes to be accessible
outside of the RHEL host ?

No, this setting is for allowing services on host to be access on the VM or by any container on openshift side. 

>Is there any way to do that with this new 4.8 based crc version ?

If you want to access your cluster outside of host then check https://crc.dev/crc/#setting-up-remote-server_gsg

**Comment by praveenkumar** [comment] 2021-09-15 04:45
@rscher Since it is fixed I am closing this one, please reopen if still have similar issue

**Closed** 2021-09-15 05:03 UTC
Labels: kind/bug, os/linux, nested-virt
