### ISSUE TITLE
[BUG] crc freeze on KVM / Virtualbox

### ISSUE THREAD

**Issue by jagusztinl** [code-ready/crc#1031] opened 2020-02-20 20:29 UTC
### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? YES

## CRC version
# Put `crc version` output here
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)
```
  
## CRC status
```bash
# Put `crc status` output here
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     10.57GB
Cache Directory: /home/crc/.crc/cache

## CRC config
```bash
# Put `crc config view` output here
```
./crc config view ----no output

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

### Steps to reproduce

  1. Install Virtualbox 6.1.4, enable HW virtualization (VT-X) 
  2. Install Centos 8, Ubuntu, Redhat linux (tried all)
  3. Install CRC
  4. start CRC - FREEZE the VM

BUT:

 1. Install VMware workstation 15.0, enable HW virtualization (VT-X) 
  2. Install Centos 8, Ubuntu, Redhat linux (tried all)
  3. Install CRC
  4. start CRC - working perfectly

### Expected
starting crc

### Actual
freeze the VM on Virtualbox with native KVM HW VT-X

### Logs
[crc@localhost crc-linux-1.6.0-amd64]$ ./crc start --log-level debug
DEBU No new version available. The latest version is 1.6.0
INFO Checking if oc binary is cached
DEBU oc binary already cached
INFO Checking if running as non-root
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU /dev/kvm was found
INFO Checking if libvirt is installed
DEBU Checking if 'virsh' is available
DEBU 'virsh' was found in /usr/bin/virsh
INFO Checking if user is part of libvirt group
DEBU Checking if current user is part of the libvirt group
DEBU Running '/usr/bin/groups crc'
DEBU Current user is already in the libvirt group
INFO Checking if libvirt is enabled
DEBU Checking if libvirtd.service is enabled
DEBU Running '/usr/bin/systemctl is-enabled libvirtd'
DEBU libvirtd.service is already enabled
INFO Checking if libvirt daemon is running
DEBU Checking if libvirtd.service is running
DEBU Running '/usr/bin/systemctl is-active libvirtd'
DEBU libvirtd.service is already running
INFO Checking if a supported libvirt version is installed
DEBU Checking if libvirt version is >=3.4.0
DEBU Running 'virsh -v'
INFO Checking if crc-driver-libvirt is installed
DEBU Checking if crc-driver-libvirt is installed
DEBU Running '/home/crc/.crc/bin/crc-driver-libvirt version'
DEBU crc-driver-libvirt is already installed in /home/crc/.crc/bin/crc-driver-libvirt
INFO Checking if libvirt 'crc' network is available
DEBU Checking if libvirt 'crc' network exists
DEBU Running 'virsh --connect qemu:///system net-info crc'
DEBU Checking if libvirt 'crc' definition is up to date
DEBU Running 'virsh --connect qemu:///system net-dumpxml --inactive crc'
DEBU libvirt 'crc' network has the expected value
INFO Checking if libvirt 'crc' network is active
DEBU Checking if libvirt 'crc' network is active
DEBU Running 'virsh --connect qemu:///system net-info crc'
DEBU libvirt 'crc' network is already active
INFO Checking if NetworkManager is installed
DEBU Checking if 'nmcli' is available
DEBU 'nmcli' was found in /usr/bin/nmcli
INFO Checking if NetworkManager service is running
DEBU Checking if NetworkManager.service is running
DEBU Running '/usr/bin/systemctl is-active NetworkManager'
DEBU NetworkManager.service is already running
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
DEBU Checking NetworkManager configuration
DEBU NetworkManager configuration is good
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
DEBU Checking dnsmasq configuration
DEBU dnsmasq configuration is good
Checking file: /home/crc/.crc/machines/crc/.crc-exist
Found binary path at /home/crc/.crc/bin/crc-driver-libvirt
Launching plugin server for driver libvirt
Plugin server listening at address 127.0.0.1:32851
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(crc) Calling .GetBundleName
(crc) Calling .GetState
(crc) DBG | Getting current state...
(crc) DBG | Fetching VM...
INFO Starting CodeReady Containers VM for OpenShift 4.3.0...
(crc) Calling .Start
(crc) DBG | Starting VM crc -----FREEZE the VM, only reset helps

**Comment by jagusztinl** [comment] 2020-02-20 20:33
Important: KVM works perfectly on the host, able to start any other VM (Centos, Ubuntu..) only CRC VM freeze

**Comment by jagusztinl** [comment] 2020-02-20 20:35
KVM debug:

Hangs immediately after this:

2020-02-16 09:02:28.320+0000: starting up libvirt version: 4.5.0, package: 35.2.module_el8.1.0+266+ba744077 (CentOS Buildsys <bugs@…>, 2020-02-04-22:03:54, ), qemu version: 2.12.0qemu-kvm-2.12.0-88.module_el8.1.0+266+ba744077.2, kernel: 4.18.0-147.el8.x86_64, hostname: localhost.localdomain LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin QEMU_AUDIO_DRV=none /usr/libexec/qemu-kvm -name guest=crc,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-crc/master-key.aes -machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off -cpu host -m 7813 -realtime mlock=off -smp 4,sockets=4,cores=1,threads=1 -uuid 7a79dc16-4a13-4f2c-81d5-6f2fcf7af65e -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=29,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot menu=off,strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x4 -drive file=/home/crc/.crc/machines/crc/crc,format=qcow2,if=none,id=drive-virtio-disk0,aio=threads -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=31,id=hostnet0,vhost=on,vhostfd=32 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:fd:fc:07:21:82,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev pty,id=charchannel0 -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -vnc 127.0.0.1:0 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -object rng-random,id=objrng0,filename=/dev/random -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x7 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on 2020-02-16 09:02:28.320+0000: Domain id=1 is tainted: host-cpu

**Comment by jagusztinl** [comment] 2020-02-20 20:36
info: <capabilities>

<host>

<uuid>0682cf7e-111f-9045-a430-71558cc0add1</uuid> <cpu>

<arch>x86_64</arch> <model>Westmere</model> <vendor>Intel</vendor> <topology sockets='1' cores='4' threads='1'/> <feature name='vme'/> <feature name='ht'/> <feature name='pclmuldq'/> <feature name='vmx'/> <feature name='pcid'/> <feature name='x2apic'/> <feature name='movbe'/> <feature name='xsave'/> <feature name='osxsave'/> <feature name='avx'/> <feature name='rdrand'/> <feature name='hypervisor'/> <feature name='fsgsbase'/> <feature name='avx2'/> <feature name='invpcid'/> <feature name='rdseed'/> <feature name='clflushopt'/> <feature name='md-clear'/> <feature name='rdtscp'/> <feature name='abm'/> <feature name='3dnowprefetch'/> <feature name='invtsc'/> <pages unit='KiB' size='4'/> <pages unit='KiB' size='2048'/>

</cpu> <power_management>

<suspend_mem/> <suspend_disk/> <suspend_hybrid/>

</power_management> <iommu support='no'/> <migration_features>

<live/> <uri_transports>

<uri_transport>tcp</uri_transport> <uri_transport>rdma</uri_transport>

</uri_transports>

</migration_features> <topology>

<cells num='1'>

<cell id='0'>

<memory unit='KiB'>9840304</memory> <pages unit='KiB' size='4'>2460076</pages> <pages unit='KiB' size='2048'>0</pages> <distances>

<sibling id='0' value='10'/>

</distances> <cpus num='4'>

<cpu id='0' socket_id='0' core_id='0' siblings='0'/> <cpu id='1' socket_id='0' core_id='1' siblings='1'/> <cpu id='2' socket_id='0' core_id='2' siblings='2'/> <cpu id='3' socket_id='0' core_id='3' siblings='3'/>

</cpus>

</cell>

</cells>

</topology> <cache>

<bank id='0' level='3' type='both' size='8' unit='MiB' cpus='0'/> <bank id='1' level='3' type='both' size='8' unit='MiB' cpus='1'/> <bank id='2' level='3' type='both' size='8' unit='MiB' cpus='2'/> <bank id='3' level='3' type='both' size='8' unit='MiB' cpus='3'/>

</cache> <secmodel>

<model>selinux</model> <doi>0</doi> <baselabel type='kvm'>system_u:system_r:svirt_t:s0</baselabel> <baselabel type='qemu'>system_u:system_r:svirt_tcg_t:s0</baselabel>

</secmodel> <secmodel>

<model>dac</model> <doi>0</doi> <baselabel type='kvm'>+107:+107</baselabel> <baselabel type='qemu'>+107:+107</baselabel>

</secmodel>

</host>

<guest>

<os_type>hvm</os_type> <arch name='i686'>

<wordsize>32</wordsize> <emulator>/usr/libexec/qemu-kvm</emulator> <machine maxCpus='240'>pc-i440fx-rhel7.6.0</machine> <machine canonical='pc-i440fx-rhel7.6.0' maxCpus='240'>pc</machine> <machine maxCpus='240'>pc-i440fx-rhel7.0.0</machine> <machine maxCpus='384'>pc-q35-rhel7.6.0</machine> <machine canonical='pc-q35-rhel7.6.0' maxCpus='384'>q35</machine> <machine maxCpus='240'>pc-i440fx-rhel7.5.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.1.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.2.0</machine> <machine maxCpus='255'>pc-q35-rhel7.3.0</machine> <machine maxCpus='384'>pc-q35-rhel7.4.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.3.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.4.0</machine> <machine maxCpus='384'>pc-q35-rhel7.5.0</machine> <domain type='qemu'/> <domain type='kvm'>

<emulator>/usr/libexec/qemu-kvm</emulator>

</domain>

</arch> <features>

<cpuselection/> <deviceboot/> <disksnapshot default='on' toggle='no'/> <acpi default='on' toggle='yes'/> <apic default='on' toggle='no'/> <pae/> <nonpae/>

</features>

</guest>

<guest>

<os_type>hvm</os_type> <arch name='x86_64'>

<wordsize>64</wordsize> <emulator>/usr/libexec/qemu-kvm</emulator> <machine maxCpus='240'>pc-i440fx-rhel7.6.0</machine> <machine canonical='pc-i440fx-rhel7.6.0' maxCpus='240'>pc</machine> <machine maxCpus='240'>pc-i440fx-rhel7.0.0</machine> <machine maxCpus='384'>pc-q35-rhel7.6.0</machine> <machine canonical='pc-q35-rhel7.6.0' maxCpus='384'>q35</machine> <machine maxCpus='240'>pc-i440fx-rhel7.5.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.1.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.2.0</machine> <machine maxCpus='255'>pc-q35-rhel7.3.0</machine> <machine maxCpus='384'>pc-q35-rhel7.4.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.3.0</machine> <machine maxCpus='240'>pc-i440fx-rhel7.4.0</machine> <machine maxCpus='384'>pc-q35-rhel7.5.0</machine> <domain type='qemu'/> <domain type='kvm'>

<emulator>/usr/libexec/qemu-kvm</emulator>

</domain>

</arch> <features>

<cpuselection/> <deviceboot/> <disksnapshot default='on' toggle='no'/> <acpi default='on' toggle='yes'/> <apic default='on' toggle='no'/>

</features>

</guest>

</capabilities>

comment:3Changed 4 days ago by jagusztinl
config: 

<domain type='kvm'>

<name>crc</name> <uuid>7a79dc16-4a13-4f2c-81d5-6f2fcf7af65e</uuid> <memory unit='KiB'>8000000</memory> <currentMemory unit='KiB'>8000000</currentMemory> <vcpu placement='static'>4</vcpu> <os>

<type arch='x86_64' machine='pc-i440fx-rhel7.6.0'>hvm</type> <boot dev='hd'/> <bootmenu enable='no'/>

</os> <features>

<acpi/> <apic/> <pae/>

</features> <cpu mode='host-passthrough' check='none'/> <clock offset='utc'/> <on_poweroff>destroy</on_poweroff> <on_reboot>restart</on_reboot> <on_crash>destroy</on_crash> <devices>

<emulator>/usr/libexec/qemu-kvm</emulator> <disk type='file' device='disk'>

<driver name='qemu' type='qcow2' io='threads'/> <source file='/home/crc/.crc/machines/crc/crc'/> <target dev='vda' bus='virtio'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>

</disk> <controller type='usb' index='0' model='piix3-uhci'>

<address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>

</controller> <controller type='pci' index='0' model='pci-root'/> <controller type='virtio-serial' index='0'>

<address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>

</controller> <interface type='network'>

<mac address='52:fd:fc:07:21:82'/> <source network='crc'/> <model type='virtio'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>

</interface> <serial type='pty'>

<target type='isa-serial' port='0'>

<model name='isa-serial'/>

</target>

</serial> <console type='pty'>

<target type='serial' port='0'/>

</console> <channel type='pty'>

<target type='virtio' name='org.qemu.guest_agent.0'/> <address type='virtio-serial' controller='0' bus='0' port='1'/>

</channel> <input type='mouse' bus='ps2'/> <input type='keyboard' bus='ps2'/> <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'>

<listen type='address' address='127.0.0.1'/>

</graphics> <video>

<model type='cirrus' vram='16384' heads='1' primary='yes'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>

</video> <memballoon model='virtio'>

<address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>

</memballoon> <rng model='virtio'>

<backend model='random'>/dev/random</backend> <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>

</rng>

</devices>

</domain>

**Comment by jagusztinl** [comment] 2020-02-20 20:36
virtualbox guest log: 
00:00:59.028630 VMMDev: Guest Log: 16:11:56.347491 main VBoxService 6.1.2 r135662 (verbosity: 0) linux.amd64 (Jan 13 2020 12:20:51) release log 00:00:59.028664 VMMDev: Guest Log: 16:11:56.347496 main Log opened 2020-02-17T16:11:56.347483000Z 00:00:59.028740 VMMDev: Guest Log: 16:11:56.347622 main OS Product: Linux 00:00:59.028857 VMMDev: Guest Log: 16:11:56.347735 main OS Release: 4.18.0-147.el8.x86_64 00:00:59.028923 VMMDev: Guest Log: 16:11:56.347807 main OS Version: #1 SMP Wed Dec 4 21:51:45 UTC 2019 00:00:59.028978 VMMDev: Guest Log: 16:11:56.347862 main Executable: /opt/VBoxGuestAdditions-6.1.2/sbin/VBoxService 00:00:59.028992 VMMDev: Guest Log: 16:11:56.347863 main Process ID: 2499 00:00:59.029001 VMMDev: Guest Log: 16:11:56.347864 main Package type: LINUX_64BITS_GENERIC 00:00:59.033167 VMMDev: Guest Log: 16:11:56.352052 main 6.1.2 r135662 started. Verbose level = 0 00:00:59.034346 GUI: UISession::sltAdditionsChange: GA state change event came, notifying listeners 00:00:59.034378 GUI: UIMachineLogicNormal::sltCheckForRequestedVisualStateType: Requested-state=0, Machine-state=5 00:00:59.035231 VMMDev: Guest Log: 16:11:56.354115 main vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1) 00:00:59.035749 Guest Control: GUEST_MSG_REPORT_FEATURES: 0x1, 0x8000000000000000 00:00:59.048173 GUI: UISession::sltAdditionsChange: GA state really changed, notifying listeners 00:00:59.048225 GUI: UIMachineViewNormal::adjustGuestScreenSize: Adjust guest-screen size if necessary 00:00:59.048268 GUI: UISession::sltAdditionsChange: GA state change event came, notifying listeners 00:00:59.048286 GUI: UIMachineLogicNormal::sltCheckForRequestedVisualStateType: Requested-state=0, Machine-state=5 00:00:59.059541 VMMDev: Guest Log: vboxsf: g_fHostFeatures=0x8000000f g_fSfFeatures=0x1 g_uSfLastFunction=29 00:00:59.060114 VMMDev: Guest Log: vboxsf: Successfully loaded version 6.1.2 on 4.18.0-147.el8.x86_64 SMP mod_unload modversions (LINUX_VERSION_CODE=0x41200) 00:00:59.062583 VMMDev: Guest Log: 16:11:56.381464 automount vbsvcAutomounterMountIt: Successfully mounted 'Documents' on '/docs' 00:28:08.359341 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.359365 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.360613 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.361931 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.361956 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.362138 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.363315 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.363340 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.363749 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.364890 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.364915 IEM: rdmsr(0x10a) -> #GP(0) 00:28:08.365139 IEM: rdmsr(0x10a) -> #GP(0) 00:28:13.439788 VMMDev: vmmDevHeartbeatFlatlinedTimer: Guest seems to be unresponsive. Last heartbeat received 4 seconds ago

**Comment by jagusztinl** [comment] 2020-02-20 20:37
[libvirtd.zip](https://github.com/code-ready/crc/files/4232891/libvirtd.zip)

**Comment by gbraad** [comment] 2020-02-21 04:10
> Virtualbox

We have dropped VirtualBox support a few releases back.

**Comment by gbraad** [comment] 2020-02-21 04:13
> Steps to reproduce
>   Install Virtualbox 6.1.4, enable HW virtualization (VT-X)
>   Install Centos 8, Ubuntu, Redhat linux (tried all)
>   Install CRC
>   start CRC - FREEZE the VM

We do not support mutliple hypervisors on a single system. More often than not they cause unexpected behaviour. 

> BUT:
>
>   Install VMware workstation 15.0, enable HW virtualization (VT-X)
>   Install Centos 8, Ubuntu, Redhat linux (tried all)
>   Install CRC
>   start CRC - working perfectly

Same story. Although it works for you, this is not recommended.

**Comment by praveenkumar** [comment] 2020-02-21 04:14
@jagusztinl we are bit confuse about the following instructions. Are you install the centos-8 on virtualbox and then install CRC on that centos-8 machine (nested virt way) or you want to directly install CRC on virtualbox (since this is not supported) even we never tested the Virtualbox nested env test.

```
Install Virtualbox 6.1.4, enable HW virtualization (VT-X)
Install Centos 8, Ubuntu, Redhat linux (tried all)
Install CRC
start CRC - FREEZE the VM
```

**Comment by gbraad** [comment] 2020-02-21 04:33
Reading this more carefully it looks like describing a nested vritualizxation setup. This is not the usecase we target with CRC. While it is popssible to run a similar setup, it is impossible to test the multitude of possible configurations, We only do this ourselves with KVM due to necessity for automated tests in CI, but it is generally not recommended. Closing it for this reason.

**Closed by gbraad** 2020-02-21 04:33 UTC
Labels: kind/bug, resolution/wontfix

**Comment by jagusztinl** [comment] 2020-02-21 11:46
Yes, the case is nested virtualization. Hyper-V is not working paralelly on our development laptops with Virtualbox or VMware player what we use currently, so we are unable to run CRC for Windows. 
This is why we created a Centos8 VM on Virtualbox and tried to start CRC in it.

**Comment by jagusztinl** [comment] 2020-02-21 11:51
@gbraad Possible to reopen this?

**Comment by gbraad** [comment] 2020-02-21 11:58
What prevents you from using HyperV?

**Comment by doormat18** [comment] 2020-03-10 20:24
I'm seeing this exact same behavior. I understand that the scenario is not supported or recommended, but I thought I'd try to get CRC to run inside a CentOS 8 virtualbox with nested virtualization. It just hangs whenever it gets to the step where it creates the VM (inside the VM). Also, can't SSH in to the VM anymore.

**Comment by doormat18** [comment] 2020-03-10 21:01
I also tried with centos7, it gets further along but eventually freezes the VM.

**Comment by cfergeau** [comment] 2020-03-11 07:27
If you want to keep debugging this, next steps would be to get CRC VM output, either through `virsh console`, or using `virt-viewer`

**Comment by spolti** [comment] 2020-03-12 19:30
on fedora it keeps freezing/lagging the physical host, basically nothing is running than crc, no extra workloads than the defaults.

**Comment by dcdh** [comment] 2021-01-16 18:25
I've facing the same issue using libvirt inside a VirtualBox.

To make it works you need to fix the vm to one CPU. (in virtualbox the process **qemu-kvm** will use 100% of cpu usage).

To have more than one CPU and avoid the freeze, I've remove in my **vm.xml** all references to **features**. (so no features exit **acpi** and **apic**).

So I was able to run a VM with 2 CPU. However, I've got theses two consequences:
Inside virtualbox **qemu-kvm** process is using 200% of cpu usage.
Some nasty messages **kernel:watchdog: BUG: soft lockup - CPU#4 stuck for 22s! [qemu-kvm:3489]** are poping on my host.

So I gave up :(
